### ISSUE TITLE
Resizable columns in spreadsheet editor

### ISSUE THREAD

**Issue by kieranr** [owncloud/richdocuments#101]
Hi, 

I can't seem to work out how to resize the columns in spreadsheet editing.

In Excel/Libreoffice - double clicking auto-resizes, but you can also hover over a column separator and a new icon appears and you can click and resize.

None of this works on the online version.

Is this a bug with richdocuments - or other underlying bits (libreoffice or Loolswd)??

Or - is there something I am missing ?
(using master copy from yesterday 1.1.4)

Cheers

**Comment by pranavk** [comment]
This is bug with libreoffice online repo, nothing to do with richdocuments.

Could you please file it there: https://bugs.documentfoundation.org/enter_bug.cgi?product=LibreOffice%20Online

**Comment by timar** [comment]
Work is in progress on column/row resizing feature, but as @pranavk said, it does not belong to here.
