### ISSUE TITLE
PLEASE! HELP! I need working release of LibreOffice Online into OwnCloud 

### ISSUE THREAD

**Issue by francescobianco** [owncloud/richdocuments#117]
Hi! 

i need a working release, please help me to configure a correct combination of
 - OS: Ubuntu or another one?
 - Server: Apache with/what PHP version?
 - Which use the correct version owncloud to make the system work?
 - there are particural server configuration or optimization?

PLEASE it is another question:
what is the expected date for the release of functioning beta is easy to use?

**Comment by MariusBluem** [comment]
You will find more information here:
https://www.collaboraoffice.com/code/

Next to a VM (called CODE) with a preconfigured Instance of ownCloud with CODE there is also a docker-image which makes it easy to install it 😁 

Nextcloud is also providing some easy setup instructions 😉 ...you'll find the link on the collabora page!

**Comment by DeepDiver1975** [comment]
THX @MariusBluem - That should help @francescobianco -> close

**Comment by francescobianco** [comment]
Every founded file not work!!!
- VirtualBox Image is corrupted
- Docker not run

**Comment by MariusBluem** [comment]
Giving 👎 as a reaction to @DeepDiver1975's and my comment about that does not help. I have given a link which should help you out (also with an step-by-step Guide!) ... if you have Problems with the Image you can explain what this Problem is about ... and then we would be happy to help you out!

**Comment by digination** [comment]
I think you should rebuild and push a new docker image, because of  #107 (lots of people had problems running the docker image back then) , and if the vbox image is also impacted, then you should rebuild it too.

**Comment by francescobianco** [comment]
My SORRY!!!!
