### ISSUE TITLE
After updating collabora on Nextcloud cannot access documents

### ISSUE THREAD

**Issue by dom134** [owncloud/richdocuments#127]
I did have a working Collabora office app working, but recently updated. Now I am unable to open any documents. The post-update error message states:

    Well, this is embarrassing, we cannot connect to your document. Please try again.

My docker log [urls and ips changed] states:

    wsd-00024-05 00:06:02.225755 [ client_req_hdl ] Request from 172.17.0.1:47716: POST /loleaflet/1.8.4/loleaflet.html?WOPISrc=https%3A%2F%2Fwww.dom134.com%2Fnextcloud%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F203620&title=php.odt&lang=en&closebutton=1&revisionhistory=1 HTTP/1.1 / Host: office.dom134.com / User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0 / Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8 / Accept-Language: en-US,en;q=0.5 / Accept-Encoding: gzip, deflate, br / DNT: 1 / Upgrade-Insecure-Requests: 1 / Content-Type: application/x-www-form-urlencoded / X-Forwarded-For: 88.88.888.888 / X-Forwarded-Host: office.dom134.com / X-Forwarded-Server: office.dom134.com / Connection: Keep-Alive / Content-Length: 45
    wsd-00024-05 00:06:02.226076 [ client_req_hdl ] Preprocessing file: /usr/share/loolwsd//loleaflet/dist/loleaflet.html
    wsd-00024-02 00:06:03.634363 [ client_req_hdl ] Request from 172.17.0.1:47720: GET /lool/https%253A%252F%252Fwww.dom134.com%252Fnextcloud%252Findex.php%252Fapps%252Frichdocuments%252Fwopi%252Ffiles%252F203620%3Faccess_token=qeUnp2EEXI6F0IlJLBU7cwiSmV8PiLwd/ws HTTP/1.1 / Host: office.dom134.com / User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0 / Accept: text/html,application/xhtml+xml,application/xml;q=0.9,/;q=0.8 / Accept-Language: en-US,en;q=0.5 / Accept-Encoding: gzip, deflate, br / Sec-WebSocket-Version: 13 / origin: https://office.dom134.com / Sec-WebSocket-Extensions: permessage-deflate / Sec-WebSocket-Key: 5JfxEr5wtG4iVaUk/ToVJQ== / DNT: 1 / Pragma: no-cache / Cache-Control: no-cache / X-Forwarded-For: 88.88.888.888 / X-Forwarded-Host: office.dom134.com / X-Forwarded-Server: office.dom134.com / Connection: Keep-Alive
    wsd-00024-02 00:06:03.634495 [ client_req_hdl ] Handling GET: /lool/https%253A%252F%252Fwww.dom134.com%252Fnextcloud%252Findex.php%252Fapps%252Frichdocuments%252Fwopi%252Ffiles%252F203620%3Faccess_token=qeUnp2EEXI6F0IlJLBU7cwiSmV8PiLwd/ws
    wsd-00024-02 00:06:03.634559 [ client_ws_0004 ] Thread started.
    wsd-00024-02 00:06:03.634606 [ client_ws_0004 ] Post request: [/lool/https%253A%252F%252Fwww.dom134.com%252Fnextcloud%252Findex.php%252Fapps%252Frichdocuments%252Fwopi%252Ffiles%252F203620%3Faccess_token=qeUnp2EEXI6F0IlJLBU7cwiSmV8PiLwd/ws]
    wsd-00024-02 00:06:03.634723 [ client_ws_0004 ] ClientRequestHandler::handleRequest: BadRequestException: Invalid or unknown request.
    wsd-00024-02 00:06:03.634801 [ client_ws_0004 ] Thread finished.

**Comment by bariera** [comment]
I have the same problem :(
[ client_ws_002f ] ClientRequestHandler::handleRequest: BadRequestException: Invalid or unknown request.

I found a workaround that works for me - migrate from Apache ReverseProxy to nginx (both from Centos repo). Platform: Centos 7.2.1511 with full update.
I know it's silly, but it works :)

I'm looking forward to the update collabora/code or richdocuments

Regards
  Artur

**Comment by dom134** [comment]
Thanks Artur,
I am using Ubuntu 16.04 and Apache2.  I have never used nginx and hang quite a few other applications from the server; therefore I think I might wait for collabora/code to be updated - I'm just a scaredy cat!

**Comment by dom134** [comment]
Hello, got the answer here:
https://help.nextcloud.com/t/updated-collabora-now-unable-to-open-documents/4179/15
Thank you for everyone's help
