### ISSUE TITLE
Collabora Online API

### ISSUE THREAD

**Issue by jwillmer** [owncloud/richdocuments#129]
Hi, I would like to connect to Collabora Online with my ASP.NET project to edit files but I can't find there API description. The only page i found is empty: [Collabora Online editor API reference](https://www.collaboraoffice.com/collabora-online-editor-api-reference/)

Could you point me to the API description you used?

**Comment by timar** [comment]
Hi @jwillmer,

The JS API reference is not empty for me, I can see everything on https://www.collaboraoffice.com/collabora-online-editor-api-reference/
However, if you want to integrate Collabora Online, you have to implement the WOPI protocol. Can you please tell me more about your project?

**Comment by jwillmer** [comment]
@timar now I see the API reference as well. I develop a ASP.NET website that collects company manuals and I like to setup a local Collabora server to enable users to edit the manuals in the browser. 

Is [this the WOPI protocol](https://msdn.microsoft.com/en-us/library/hh622722(v=office.12).aspx) you are refering to? Do you know if there are examples on how to connect to Collabora in C# or Java?

**Comment by jwillmer** [comment]
I found this image at [msdn](https://code.msdn.microsoft.com/office/Building-an-Office-Web-f98650d6) and as I understand my ASP.NET website would be the WOPI server that knows the url of the WOPI client (Collabora). 
![7128 intro_5f00_wopi_5f00_5c7408b7 5b1 5d](https://cloud.githubusercontent.com/assets/1503577/19563390/6c5a127e-96e8-11e6-9837-36557fe5806e.jpg)

I also found the [WOPI REST endpoints](http://wopi.readthedocs.io/projects/wopirest/en/latest/endpoints.html) I think I am now good to go. 

Thank you @timar !

Last question, is there anything Collabora specific I need to know?
