### ISSUE TITLE
Issue tracker of CODE

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/richdocuments#132]
Do you know where is the issue tracker of this docker image, or even just CODE?
https://www.collaboraoffice.com/code/

**Comment by RealRancor** [comment]
@pierreozoux I have seen people reporting issues with the docker image at:

https://bugs.documentfoundation.org/show_bug.cgi?id=101809

which got noticed and solved there.

**Comment by timar** [comment]
https://bugs.documentfoundation.org is fine, there is a LibreOffice Online component. Make sure you put me (timar74@gmail.com) in CC.
