### ISSUE TITLE
Works but When I exit CRASH

### ISSUE THREAD

**Issue by klendazu** [owncloud/richdocuments#155]
I have installed on Ubuntu 14.0.4.5 LTS and owncloud 8.2
I run loolwsd, everything works fine, i edit a document, when i press the exit boton the loolwsd CRASH.
I paste the debug info
loolwsd
loolforkit version details: 2.0.1+ - 9c35ab1
office version details: { "ProductName": "LibreOfficeDev", "ProductVersion": "5. 4", "ProductExtension": ".0.0.alpha0", "BuildId": "1b5e144b4ed0e276d6485ece6d3d2 b0b10f9bbf8" }
wsd-21942-21945 0:00:46.412351 [ client_ws_0002 ] SIG Fatal signal received: S IGSEGV
Backtrace 21942:
./loolwsd() [0x4c5f87]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7f8478e2f330]
./loolwsd(_ZN14DocumentBroker13removeSessionERKSs+0x14e) [0x44547e]
./loolwsd(_ZN20ClientRequestHandler17processGetRequestERKSsRSt10shared_ptrI13LOO LWebSocketES1_RKN4Poco3URIERKS2_I14DocumentBrokerEb+0x98d) [0x46b8ad]
./loolwsd(_ZN20ClientRequestHandler16handleGetRequestERKSsRSt10shared_ptrI13LOOL WebSocketES1_+0x946) [0x471126]
./loolwsd(_ZN20ClientRequestHandler19handleClientRequestERN4Poco3Net17HTTPServer RequestERNS1_18HTTPServerResponseE+0x10bc) [0x478f4c]
./loolwsd(_ZN20ClientRequestHandler13handleRequestERN4Poco3Net17HTTPServerReques tERNS1_18HTTPServerResponseE+0x33b) [0x47a5bb]
/opt/poco/lib/libPocoNetd.so.44(_ZN4Poco3Net20HTTPServerConnection3runEv+0x30c) [0x7f847a85c21e]
/opt/poco/lib/libPocoNetd.so.44(_ZN4Poco3Net19TCPServerConnection5startEv+0x24) [0x7f847a87a944]
/opt/poco/lib/libPocoNetd.so.44(_ZN4Poco3Net19TCPServerDispatcher3runEv+0x164) [ 0x7f847a890a2c]
/opt/poco/lib/libPocoFoundationd.so.44(_ZN4Poco12PooledThread3runEv+0x85) [0x7f8 479edb873]
/opt/poco/lib/libPocoFoundationd.so.44(+0x1f9d8d) [0x7f8479ed8d8d]
/opt/poco/lib/libPocoFoundationd.so.44(_ZN4Poco10ThreadImpl13runnableEntryEPv+0x e1) [0x7f8479ed8a3d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f8478e27184]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f8478b5437d]
Violación de segmento (`core' generado)

**Comment by LukasReschke** [comment]
How did you install loolwsd? Did you use the Docker?

**Comment by klendazu** [comment]
I build from source.

**Comment by LukasReschke** [comment]
=> Then that is out of our responsibility. There's not much we can do here, we don't offer support for builds from source for LibreOffice Online.

Maybe try the LibreOffice mailing list, or bugtracker or so…
