### ISSUE TITLE
install LibreOffice Online WebSocket Daemon

### ISSUE THREAD

**Issue by umarzuki** [owncloud/richdocuments#156]
how do I install loolswd? Please include steps to get it up and running. At least for ubuntu lts

**Comment by umarzuki** [comment]
found that I can install collabora but when opening Office apps from owncloud, it failed with:

Collabora Online unknown error: cURL error 52: Empty reply from server

Please contact the "http://127.0.0.1:9980>" administrator.

**Comment by dias3000** [comment]
https://www.collaboraoffice.com/code/
