### ISSUE TITLE
Richdocuments, owncloud and collabora  letsencrypt Certs Problem Curl 60 Error

### ISSUE THREAD

**Issue by ly2ly** [owncloud/richdocuments#157]
Hello, 

I got an Curl 60 error on richdocuments.
I installed Owncloud and Collabora online without docker on the same server.
For ssl certificate, I use letsencrypt for my subdomain auth with 4 files:
- /letsencrypt/live/sub.mydomain.com/cert.pem
- /letsencrypt/live/sub.mydomain.com/chain.pem
- /letsencrypt/live/sub.mydomain.com/fullchain.pem
- /letsencrypt/live/sub.mydomain.com/privkey.pem

I connect the different cert to apache for owncloud and to Collabora and there work well.
Here is ssl conguration I did in:
Apache virtual host
   SSLProxyEngine on
   SSLEngine on
   SSLCertificateFile /letsencrypt/live/sub.mydomain.com/cert.pem
   SSLCertificateKeyFile /letsencrypt/live/sub.mydomain.com/privkey.pem
   SSLCACertificateFile /letsencrypt/live/sub.mydomain.com/cert.pem

Collabora in loolwsd.xml
<ssl desc="SSL settings">
        <enable type="bool" default="true">true</enable>
        <termination desc="Connection via proxy where loolwsd acts as working via https, but actually uses http." type="bool" default="true">true</te$
        <cert_file_path desc="Path to the cert file" relative="false">/letsencrypt/live/sub.mydomain.com/cert.pem</cert_file_path>
        <key_file_path desc="Path to the key file" relative="false">/letsencrypt/live/sub.mydomain.com/privkey.pem</key_file_path>
        <ca_file_path desc="Path to the ca file" relative="false">/letsencrypt/live/sub.mydomain.com/cert.pem</ca_file_path>
    </ssl>

After launch of collabora, I successfuly test it with the link.
https://sub.mydomain.com:9980/loleaflet/1a926ad/loleaflet.html?file_path=file:///opt/online/test/data/hello-world.odt

But I stuck after install of Collabora Online connector 1.1.17 (https://apps.owncloud.com/content/show.php/Collabora+Online?content=174727)
I configure as Collabora Online server : https://sub.mydomain.com:9980/
and I got the message

Collabora Online: SSL certificate is not installed.
Please ask your administrator to add ca-chain.cert.pem to the ca-bundle.crt, for example "cat /etc/loolwsd/ca-chain.cert.pem >> /resources/config/ca-bundle.crt" .
The exact error message was: cURL error 60: SSL certificate problem: certificate is not yet valid

Unfortunnaly, with the version 2.0 of collabora, the loolwsd folder don't exist.
I find a folder wsd but without any cert. So I tried with the file /online/etc/ca-chain.cert.pem in command

cat /online/etc/ca-chain.cert.pem >> owncloud/resources/config/ca-bundle.crt

without result.
So which cert must I use? which file of my letsencrypt certs? I missed something?

**Comment by timar** [comment]
> cURL error 60: SSL certificate problem: certificate is not yet valid
	
Is your server's date/time correct?

**Comment by ly2ly** [comment]
No It wasn't. 
After date/time correction, it work. Thanks

**Comment by ly2ly** [comment]
hello @timar  Thanks for your help, but I got an other error.
I change IP, Dns and letsenscrypt cert of my server. All is OK, I can see the hello test doc without problem.  but richdocument stuck when try to open a doc.
I got error 
Service is unavailable. Please try again later and report to your administrator if the issue persists.
I tried again and again without succes.
In Owncloud, I got these errors:
{"reqId":"duEeN6LT6Ty\/Lsx5msic","remoteAddr":"41.202.74.222","app":"PHP","message":"Undefined index: filename at \/var\/www\/owncloud\/apps\/richdocuments\/controller\/documentcontroller.php#363","level":3,"time":"2017-02-01T22:11:57+00:00","method":"POST","url":"\/drive\/index.php\/apps\/richdocuments\/ajax\/documents\/create","user":"admin"}
{"reqId":"duEeN6LT6Ty\/Lsx5msic","remoteAddr":"41.202.74.222","app":"PHP","message":"Undefined index: dir at \/var\/www\/owncloud\/apps\/richdocuments\/controller\/documentcontroller.php#364","level":3,"time":"2017-02-01T22:11:57+00:00","method":"POST","url":"\/drive\/index.php\/apps\/richdocuments\/ajax\/documents\/create","user":"admin"}
{"reqId":"4y6rdH+faAWgIDz0XNey","remoteAddr":"41.202.74.222","app":"PHP","message":"Undefined index: filename at \/var\/www\/owncloud\/apps\/richdocuments\/controller\/documentcontroller.php#363","level":3,"time":"2017-02-01T22:12:04+00:00","method":"POST","url":"\/drive\/index.php\/apps\/richdocuments\/ajax\/documents\/create","user":"admin"}
{"reqId":"4y6rdH+faAWgIDz0XNey","remoteAddr":"41.202.74.222","app":"PHP","message":"Undefined index: dir at \/var\/www\/owncloud\/apps\/richdocuments\/controller\/documentcontroller.php#364","level":3,"time":"2017-02-01T22:12:04+00:00","method":"POST","url":"\/drive\/index.php\/apps\/richdocuments\/ajax\/documents\/create","user":"admin"}

**Comment by kdslkdsaldsal** [comment]
@ly2ly So why keep this open then? 😄
