### ISSUE TITLE
Richdocument can't open a doc

### ISSUE THREAD

**Issue by ly2ly** [owncloud/richdocuments#158]
I change IP, Dns and letsenscrypt cert of my server. All is OK, 
I install Owncloud and collabora on a save server. I use letsenscrypt cert for https.
I can see the hello test doc of collabora without problem but richdocument stuck when try to open a doc and I got error
Service is unavailable. Please try again later and report to your administrator if the issue persists.
I tried again and again without succes.

In Owncloud, I got these lines:
{"reqId":"duEeN6LT6Ty/Lsx5msic","remoteAddr":"411.202.74.222","app":"PHP","message":"Undefined index: filename at /var/www/owncloud/apps/richdocuments/controller/documentcontroller.php#363","level":3,"time":"2017-02-01T22:11:57+00:00","method":"POST","url":"/drive/index.php/apps/richdocuments/ajax/documents/create","user":"admin"}
{"reqId":"duEeN6LT6Ty/Lsx5msic","remoteAddr":"IP","app":"PHP","message":"Undefined index: dir at /var/www/owncloud/apps/richdocuments/controller/documentcontroller.php#364","level":3,"time":"2017-02-01T22:11:57+00:00","method":"POST","url":"/drive/index.php/apps/richdocuments/ajax/documents/create","user":"admin"}
{"reqId":"4y6rdH+faAWgIDz0XNey","remoteAddr":"IP","app":"PHP","message":"Undefined index: filename at /var/www/owncloud/apps/richdocuments/controller/documentcontroller.php#363","level":3,"time":"2017-02-01T22:12:04+00:00","method":"POST","url":"/drive/index.php/apps/richdocuments/ajax/documents/create","user":"admin"}
{"reqId":"4y6rdH+faAWgIDz0XNey","remoteAddr":"IP","app":"PHP","message":"Undefined index: dir at /var/www/owncloud/apps/richdocuments/controller/documentcontroller.php#364","level":3,"time":"2017-02-01T22:12:04+00:00","method":"POST","url":"/drive/index.php/apps/richdocuments/ajax/documents/create","user":"admin"}

**Comment by nobody4242** [comment]
i had this too - solution was from:
https://help.nextcloud.com/t/collabora-docker-capabilities-problem/4774/14

Steps to solve:

docker ps (to get the id)
docker stop [id]
docker rm [id]

then changed /etc/default/docker

# Use DOCKER_OPTS to modify the daemon startup options.
DOCKER_OPTS="--storage-driver=devicemapper"

restarted docker
and started collabora again which downloaded a new image and is running perfect now
