### ISSUE TITLE
Not found - The requested document was not found on this server.

### ISSUE THREAD

**Issue by neon-it** [owncloud/richdocuments#18]
Hello, i have activation this application to my ownCloud Server 8.2.2
So, if i want to open an example document the url is switching to /index.php/apps/richdocuments/index#4 and i see "Collabora Online" in the header - but in the content area it shows me an error "Not found - The requested document was not found on this server." This happens to all .ODT and .ODS files i tested.

**Comment by timar** [comment]
Installing this app alone will not do anything. This app integrates the backend into ownCloud. Installing the backend is a much more involved effort, and it is still in development. Best to get the pre-built VM and take it for a spin to get a taste of what's to come when CODE is released. See https://www.collaboraoffice.com/code/
