### ISSUE TITLE
New release 1.1.24 is missing at marketplace

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/richdocuments#186]
Hi *,

just have noticed that the old appstore has version 1.1.24

https://apps.owncloud.com/content/show.php/Collabora+Online+connector?content=174727

where the marketplace has only 1.1.23:

https://marketplace.owncloud.com/apps/richdocuments

Is there any reason for this? I would expect that the marketplace has at least the same version then the old appstore.

**Comment by timar** [comment]
Hi,

Thanks for the bug report. Marketplace developers innovated the "planned" state, that was not there before, as far as I'm concerned, and the app was stuck in "planned" state. Now I pushed it to "published" state.
