### ISSUE TITLE
How to get the required /cloudsuite

### ISSUE THREAD

**Issue by remarklin** [owncloud/richdocuments#2]
as title

**Comment by ozcanesen** [comment]
Hello remarklin,

You can try https://www.collaboraoffice.com/code/ , It contains both CloudSuite and Richdocuments, including pre-configured loolwsd server and all other required things. 

Best,

**Comment by Ark74** [comment]
So it means so far no Debian/*buntu (or any other distro) implementation of CODE for ownCloud, right?

**Comment by ozcanesen** [comment]
@Ark74 Yes, there is no package right now.
