### ISSUE TITLE
Public Link downloads file instead of editing

### ISSUE THREAD

**Issue by toddviau** [owncloud/richdocuments#208]
I created a public link to a folder and set the security to Read & Write. When using this link and clicking on a document in the folder, it downloads the file instead of editing it. A logged in user in this folder not using the public link can edit just fine. If I try to create a public link for the document, the only option I have is Read only. Is this a setting I'm missing or is it not possible to edit a document in a public share?

**Comment by mrow4a** [comment]
Resolved by https://github.com/owncloud/richdocuments/releases/tag/2.1.0
