### ISSUE TITLE
fix github releases

### ISSUE THREAD

**Issue by felixboehm** [owncloud/richdocuments#214]
https://github.com/owncloud/richdocuments/releases

The released app on github and on marketplace differ.
I would expect them to be equal.

On github release, 
- the tar.gz contains lots of unneaded files
- is not signed
- the unpacked folder is not the appname, instead is richdocuments-2.0.5

**Comment by timar** [comment]
Github release is made automatically from the source code (source release). I can upload the signed app package in addition.

**Comment by timar** [comment]
I added the signed app to release 2.0.6
