### ISSUE TITLE
[QA] ci setup needs attention

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/richdocuments#229]
- [x] no tests with owncloud10
- [x] no tests are executed
- [x] move to drone
- [x] add phpstan
- [x] add phan
- [x] add php-cs-fixer
- [x] add to nightly drone jobs - @phil-davis PR for this in gitea has been merged - ToDo, check on Wed 2018-12-19 if nightly drone job ran OK.

Part of issue https://github.com/owncloud/QA/issues/582

**Comment by mrow4a** [comment]
To close this ticket properly small refactor will be needed. This is to allow cover with unit test class functionalities - currently, it is very difficult in many places.

**Comment by mrow4a** [comment]
Assigning myself as @skshetry already did awesome job.

**Comment by phil-davis** [comment]
drone CI is running nightly, passed last night. QA-team items are done.

**Comment by mrow4a** [comment]
@DeepDiver1975 @phil-davis we can also create new issue for unit tests/integration tests and close this one too.

**Comment by phil-davis** [comment]
@mrow4a Sounds good to me - open an issue, reference it here and close this issue.

**Comment by mrow4a** [comment]
https://github.com/owncloud/richdocuments/issues/242
