### ISSUE TITLE
richdocuments does not go back to folder after closing a document anymore

### ISSUE THREAD

**Issue by Rudloff** [owncloud/richdocuments#238]
Hello,

Since #208, when closing LibreOffice Online (with the red close button in the toolbar), it goes back to `/apps/richdocuments/index`.
Before that, it went back to the folder containing the document, which IMHO makes a lot more sense.

Also (probably a side effect), when viewing a publicly shared document without an account and closing it, it tries to go back to `/apps/richdocuments/index` but does not have enough rights and ends up looping back to the document.

**Comment by mrow4a** [comment]
@Rudloff thanks for reporting the issue, it will certainly speed up merging of the fix. It was side effect of adding larger change. We have plans on adding integration tests coverage in the future, which will prevent such regressions.
