### ISSUE TITLE
Save As does not work

### ISSUE THREAD

**Issue by timar** [owncloud/richdocuments#246]
From Collabora Online, try to rename a file (Save As...). The following error will be shown:

"Failed to read document from storage. Please contact your storage server (staging.us.collaboraonline.com) administrator."

This is a regression, it used to work. 
Seen with richdocuments 2.1.1

**Comment by thebearon** [comment]
Bisection shows that the bug started with either of the following commits:
7e032f83ca1355f5e5322171b3065cc12c7553c3
e2cfa54e52620009833d9f90fb98058121f42285
1c32ef37dfc6b62aa656467f21652d28bb62b43e

CC @mrow4a, could you please take a look?

**Comment by mrow4a** [comment]
It is possible this count introduce this regression, the code needs to be covered with unit tests (first refactored to be able too), testing everything manually would be very difficult. We have plan to do that.

**Comment by ctscobra** [comment]
HI any update re this , we experience same issue. Document is created but messages are spamming.

**Comment by timar** [comment]
This bug has been fixed by PR #247 and the fix has been released in richdocument version 2.1.2.

**Comment by titansmc** [comment]
the same here for  richdocument 2.2.0 and owncloud 10.3.2
Is this a regression ?
