### ISSUE TITLE
Make dist fails

### ISSUE THREAD

**Issue by PVince81** [owncloud/richdocuments#251]
```
rm -Rf /richdocuments; mkdir -p /richdocuments
mkdir: cannot create directory ‘/richdocuments’: Permission denied
make: *** [Makefile:79: /richdocuments] Error 1
```

seems the variable `dist_dir` is missing

**Comment by PVince81** [comment]
so far it's likely that `make appstore` was used instead for publishing, so depending how we do it in other Makefiles we could rewire this.

@phil-davis

**Comment by PVince81** [comment]
also:

- [ ] BUG: `make appstore` not working if the "core" directory is not called "core"

**Comment by phil-davis** [comment]
Also see issue #300 
`make appstore` is being used for building the release tarball.

**Comment by phil-davis** [comment]
Issue #300 and PR #302 aligned `make dist` and `make appstore`
`dist_dir` is there now, and both commands work and provide a tarball with the same contents.
