### ISSUE TITLE
Secure view tests for resharing

### ISSUE THREAD

**Issue by skshetry** [owncloud/richdocuments#265]
Implement steps for resharing when secure view is enabled. The PR #263 added some tests, but, we have not completely tested if there is privilege escalations during testing. Use api steps as well as webui steps in a scenario to  make sure it is correct and as per specification.

Also, test sharing with combination of different default secure view permissions set, and different secure view permissions set when sharing, and check what permissions do 3rd person get.

**Comment by skshetry** [comment]
Might require owncloud/core#35846 and owncloud/core#35847

**Comment by individual-it** [comment]
see https://github.com/owncloud/enterprise/issues/3441

**Comment by phil-davis** [comment]
ToDo: review if there is more useful tests to add now, or if this is better to wait until the enterprise issue is sorted out.

**Comment by phil-davis** [comment]
@dpakach can somebody see if this is done, or needs more test scenarios?

Then we can decide the priority.

**Comment by HariBhandari07** [comment]
https://github.com/owncloud/enterprise/issues/3441#issuecomment-512184426
It seems like resharing for secure view will be disabled, @phil-davis should we add more tests or close this issue?

**Comment by phil-davis** [comment]
For the resharing test scenarios, yes we should wait until the requirements about "secure view with resharing" are sorted out. The PR that implements whatever is decided, that can have the relevant tests.

@skshetry said in the OP:
```
Also, test sharing with combination of different default secure view permissions set, and different secure view permissions set when sharing, and check what permissions do 3rd person get.
```
Are there "ordinary" combinations that still need to be tested?

**Comment by phil-davis** [comment]
After discussing, we are leaving this until there is some progress about preventing resharing of secure-view shares.

**Comment by phil-davis** [comment]
IMO something happened recently about preventing of resharing of secure-view shares.
@HariBhandari07 can you find that? Did we do tests? Or are more tests needed?

**Comment by HariBhandari07** [comment]
@phil-davis according to this PR https://github.com/owncloud/core/pull/36265 reshare is disabled on a secure view. We have PR https://github.com/owncloud/richdocuments/pull/310 that ensures resharing is disabled in secure view. IMO we can close this issue.
