### ISSUE TITLE
cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/richdocuments#27]
Any ideas why this happens?

![unbenannt](https://cloud.githubusercontent.com/assets/9192953/14043774/4c028d44-f288-11e5-9346-095fcb98f636.png)

**Comment by pierrejochem** [comment]
It depends on CODE? Right? CODE is not real Open Source correct?

**Comment by timar** [comment]
The full stack is open source. CODE = LibreOffice + loolwsd + loleaflet + owncloud:richdocuments

 owncloud:richdocuments is not usable on its own.

**Comment by pierrejochem** [comment]
Thank you for the hint :+1:
