### ISSUE TITLE
Secure View options are no longer visible in the sidebar if edit option is marked

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#286]
Tested with ownCloud 10.3.0 alpha2 and richdocuments: 2.2.0RC

Example below:

Steps to reproduce:

1 - Share a file and click on edit in the sidebar.

Result: 

Can export option is no longer available.

![Screen Shot 2019-10-01 at 09 40 05](https://user-images.githubusercontent.com/10596560/65943391-a6876e00-e42f-11e9-9823-0eae48d06dc6.png)

Also other weird behavior happens 'playing' with the permissions checkboxes

![desaparecer](https://user-images.githubusercontent.com/10596560/65943554-054ce780-e430-11e9-869d-2df8cbadda96.gif)

**Comment by pmaier1** [comment]
This is expected. Secure View and "Edit" are by definition mutually exclusive.

**Comment by davitol** [comment]
But IMHO if you mark out the "Edit" option, then Secure View options should appear again, no?

**Comment by pmaier1** [comment]
> But IMHO if you mark out the "Edit" option, then Secure View options should appear again, no?

Yes, absolutely. Good catch!

**Comment by davitol** [comment]
![Screen Shot 2019-10-01 at 11 33 16](https://user-images.githubusercontent.com/10596560/65950917-4ac4e100-e43f-11e9-8d01-769e95e8f425.png)

Enabling Can share option makes the Secure View options disappear too.

**Comment by pmaier1** [comment]
> Enabling Can share option makes the Secure View options disappear too.

I think this is expected as we had to disable resharing until we have proper handling for permissions (prevent privilege escalations).

Generally speaking, when "can edit" is ticked, "Secure View" may not be ticked (the checkmark should switch when you tick each other). "can print / export" is only visible when "Secure View" is ticked. Ref. https://github.com/owncloud/enterprise/issues/2917#issuecomment-492712169

**Comment by mrow4a** [comment]
@davitol can you give me step by step instructions what to do to reproduce that UX glitch?

**Comment by davitol** [comment]
> @davitol can you give me step by step instructions what to do to reproduce that UX glitch?

Retested from a fresh server and I cannot longer reproduce it... If i'm able to reproduce it again consistently I will reopen the ticket
