### ISSUE TITLE
Cannot sync files shared with Secure View using Desktop Client 

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#287]
Tested with oC 10.3 RC1, Desktop Client for Mac 2.6.0beta1 and richdocuments 2.2.0 RC 

### Steps to reproduce

1 - Configure an account in Desktop client for user1
2 - Share a *.odt file from admin to user1 using webUI with Secure options enabled

### Expected result

File should appear in user1 Desktop client account

### Current behavior

An exception is shown in logs and the file does not appear in the Desktop folder

### owncloudsys.log  (owncloud Desktop log)

```
#=#=#=#=# Propagation starts 2019-10-01T08:03:37Z (last step: 3250 msec, total: 3250 msec)
08:03:37||ExternalStorage.odt|INST_NEW|Down|1529486912|25d12ef84433f0e52ccdf77e9bcca386|1959898|00000055ocv8u3echz9a|2|Server replied "403 Forbidden" to "GET http://10.40.40.222:9681/remote.php/dav/files/admin/ExternalStorage.odt" (Access to this resource has been denied because it is in view-only mode.)|403|0|0|2929145d-698c-4e9d-b11a-0fc69d5e1c9b
```

### owncloud.log

```
{"reqId":"2929145d-698c-4e9d-b11a-0fc69d5e1c9b","level":4,"time":"2019-10-01T08:03:38+00:00","remoteAddr":"172.24.0.1","user":"admin","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/admin\/ExternalStorage.odt","message":"Exception: HTTP\/1.1 403 Access to this resource has been denied because it is in view-only mode.: {\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\Forbidden\",\"Message\":\"Access to this resource has been denied because it is in view-only mode.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): OCA\\\\DAV\\\\DAV\\\\ViewOnlyPlugin->checkViewOnly(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:GET', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/DAV\\\/ViewOnlyPlugin.php\",\"Line\":109}"}
```

(@pmaier1 @mrow4a JFYI)

**Comment by DeepDiver1975** [comment]
> ### Expected result
> 
> File should appear in user1 Desktop client account

No - secure view means: You cannot download the file - with no mechanism at all - this includes desktop client

**Comment by mrow4a** [comment]
@davitol this is expected, sync client should also blacklist file properly - if this is not the case, this would be a bug (or any other user impacting scenario or priviledge escalation)

**Comment by phil-davis** [comment]
@davitol the issues here will be more about the user experience in each client when there is a "secure view" file on the server. And the user experience might need improving on each client as the clients are taught about these possibilities. e.g.

- does the client keep trying to download/sync over-and-over and spams both client and server logs too much?
- does the client display "nasty red errors" to the user, or are they shown as "nicer" warnings or info with explanations that a user could understand?
...

The user experience in webUI, phoenix, desktop, Android and iOS would need to be ttried and "fixed/adjusted" in future client releases.

**Comment by davitol** [comment]
> No - secure view means: You cannot download the file - with no mechanism at all - this includes desktop client

Ok understood i thought file should be downloaded as PDF  with marks or something similar.  Thanks everybody the feedback.

@mrow4aI Feel free to close the ticket or keep it opened for taking into account the comments made by @phil-davis here:
https://github.com/owncloud/richdocuments/issues/287#issuecomment-536927385

**Comment by mrow4a** [comment]
@davitol not richdocuments app related, and cannot be solved here. Closing
