### ISSUE TITLE
Weird behavior when checking Secure View options

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#288]
Tested with Chrome, when configuring Secure view options in Collabora menu

![optionsCola](https://user-images.githubusercontent.com/10596560/65959666-e449be00-e452-11e9-98cf-ea895b3569fb.gif)

(@mrow4a JFYI)

**Comment by phil-davis** [comment]
I guess that it is not sensible to have Secure View enabled, but both options off. That would result in documents that cannot be viewed in any way (no download, no print/export, no "image in the browser with watermarks).

If there is no way to view the document at all, then there would be no point in sharing.

**Comment by mrow4a** [comment]
@davitol I know that this is ugly, but making that properly would require to put there proper JS code. Currently this is static HTML and e.g. I cannot hide things etc, this would require larger refactor of the app @pmaier1

**Comment by pmaier1** [comment]
> I guess that it is not sensible to have Secure View enabled, but both options off. That would result in documents that cannot be viewed in any way (no download, no print/export, no "image in the browser with watermarks).

These are just defaults, meaning when both are unticked, each share would simply not be a Secure View share by default (it would be read-only/viewer). If both are ticked, each share would. But users can deviate. Still, "can print / export" without "Secure View" doesn't make much sense and is even prevented in the sharing dialog.

> Currently this is static HTML and e.g. I cannot hide things etc, this would require larger refactor of the app @pmaier1

So we have to accept this unless we want to spend much more time?

**Comment by mrow4a** [comment]
This is the best what I can do without refactor - https://github.com/owncloud/richdocuments/pull/294

**Comment by pmaier1** [comment]
I just tried this with 2.2.0. The behavior is not as described in https://github.com/owncloud/richdocuments/pull/294#issue-325713260. If I tick one of the defaults checkboxes, there's no way to disable both checkboxes as the checkmark jumps to the other checkbox when I try to untick it. The "can print / export" checkbox is not greyed-out.

**Comment by mrow4a** [comment]
@pmaier1 can you somehow record it and point what is the non- expected behaviour? Thanks!

**Comment by davitol** [comment]
As far as I remember when I tested it , i think it was fine if there's no way to disable both checkboxes as the checkmark jumps to the other checkbox when you try to untick it. Because I think it is nonsense to have Secure View option enabled and no options marked. Anyway as @mrow4a said please show us what you would expect. Sorry for the confusion.

**Comment by pmaier1** [comment]
Sorry, I tested with RC1 accidentally. The behavior in final is ok-ish. Still, you can't disable both by default, meaning if you do not set Secure View by default and a user enables it, the "can print" option is also enabled by default. Best case it would be possible to disable/enable both independently, I think.

> I think it is nonsense to have Secure View option enabled and no options marked. 

Why this? This means that you want to set regular sharing defaults, like read-only or edit and Secure View (as well as "can print") needs to be enabled by the user if they intend to.
