### ISSUE TITLE
Typo in Encryption warning message

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#289]
<img width="787" alt="Screen Shot 2019-10-02 at 10 11 21" src="https://user-images.githubusercontent.com/10596560/66028398-4e1ea200-e4fd-11e9-8b7e-ddfa893c40bf.png">

**Comment by davitol** [comment]
Not only the typo in 'priviledged' but also why the message refers to 'user key is enabled' when the Default encryption module i have used is Master key. 


<img width="679" alt="Screen Shot 2019-10-02 at 10 15 39" src="https://user-images.githubusercontent.com/10596560/66028708-f2a0e400-e4fd-11e9-8ee8-db8e0e773091.png">

(@mrow4a jFYI)

**Comment by mrow4a** [comment]
@davitol thanks, I will have a look - the message indeed should not be displayed and this was overlooked.

**Comment by mrow4a** [comment]
@pmaier1 @micbar @davitol fix in https://github.com/owncloud/richdocuments/pull/292
