### ISSUE TITLE
Release build process

### ISSUE THREAD

**Issue by phil-davis** [owncloud/richdocuments#300]
`Makefile` has targets for `make appstore` and `make dist`

For this repo,
1) which of `make appstore` and `make dist` is the one actually in use during the release and signing process?
2) which is the desired one?
3) should I delete the code of the not-desired one?

Then we can sort out the detail of any problems with the selected `make` target.

Note: the decision here could be different from what is done for other ownCloud app repos - because the release process of this app is managed differently anyway.

**Comment by phil-davis** [comment]
@timar ?

**Comment by timar** [comment]
I use `make appstore` to build and sign.

**Comment by phil-davis** [comment]
Assigned myself to have a look and propose any `Makefile` adjustments.

**Comment by timar** [comment]
'make dist' packs unnecessary files, such as l10n/no-php and l10n/.tx/config.

**Comment by phil-davis** [comment]
Done on #302
