### ISSUE TITLE
cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by blackPantherOS** [owncloud/richdocuments#31]
git clone ....
enabled module 
click to uploaded odt file
I got "cURL error 3: <url> malformed" message
Not have any relevant message in owncloud.log

**Comment by shwarz13** [comment]
administration -> Collabora Online
WOPI Client
https://localhost:9980 replace
https://loolwsd-servers.example.my:9980

**Comment by shwarz13** [comment]
owncloud9.0.0
administration->Collabora Online
WOPI Client
`https://localhost:9980` replace
`https://loolwsd-server.example.my:9980`

**Comment by cooperrj** [comment]
Same problem.

**Comment by shwarz13** [comment]
owncloud9.0
Administration -> Collabora Online
WOPI Client
 `https://localhost:9980` replace
`https://loolwsd-server.examlpe.my:9980`

**Comment by blackPantherOS** [comment]
It's not possible becuse the Owncloud running on local and intranet network

**Comment by timar** [comment]
Do you have loolwsd + loleaflet + LibreOffice master? The "richdocuments" ownCloud plugin is just an interface between ownCloud and loolwsd + loleaflet + LibreOffice. 

The WOPI Client URL has to be changed from localhost to the IP address or the domain name of the server, which is running loolwsd.

Please note that we are talking about unreleased software, which is under heavy development. You have to compile loolwsd from source yourself.
