### ISSUE TITLE
Acceptance test fails due to core changes

### ISSUE THREAD

**Issue by phil-davis** [owncloud/richdocuments#312]
https://drone.owncloud.com/owncloud/richdocuments/631/12/10

**Comment by phil-davis** [comment]
Needs core PR to be merged.

**Comment by dpakach** [comment]
Fixed by https://www.youtube.com/watch?v=NiqM3lVirkw

**Comment by dpakach** [comment]
Fixed by https://github.com/owncloud/core/pull/36673
