### ISSUE TITLE
[strictly 10.4] Richdocuments 2.3.0

### ISSUE THREAD

**Issue by micbar** [owncloud/richdocuments#314]
## Release needed for
- https://github.com/owncloud/richdocuments/pull/313

**Comment by micbar** [comment]
@jw @HanaGemela The releases have been done by @timar in the past.

You need just to coordinate.

**Comment by timar** [comment]
I can release when #313 is merged.

**Comment by micbar** [comment]
@timar We merged the fix.
We could use a release candidate, if you dont mind?

**Comment by timar** [comment]
> @timar We merged the fix.
> We could use a release candidate, if you dont mind?

Of course, but you did not bump the version number. I did, and I'm waiting for review, however I've just noticed that you may want 2.3.0 not 2.2.1. I'm travelling today and tomorrow but if you sort out the version, I can release still.

**Comment by HanaGemela** [comment]
Needs to be live before 10.4 server FYI @davitol

**Comment by HanaGemela** [comment]
@timar please create RC1 and we'll test it

**Comment by davitol** [comment]
Issues found while QA: https://github.com/owncloud/richdocuments/issues/324#issuecomment-595784709

**Comment by davitol** [comment]
@pmaier1 IMHO we maybe need a more explicit message here:

![Screen Shot 2020-03-09 at 12 14 00](https://user-images.githubusercontent.com/10596560/76208488-10d2e480-6200-11ea-9570-9cfc5be74a54.png)



## Steps to reproduce

1 - user1 shares a files with secure view to user2 (user2 cannot reshare that file)
2 - user2 moves that file into a folder
3 - user2 tries to share that folder

## Actual behavior

`Path contains files shared with you`message is shown

Feedback is welcome

**Comment by pmaier1** [comment]
> @pmaier1 IMHO we maybe need a more explicit message here:

This is not related to richdocuments, is it? 

"You can't share a folder which contains resources shared with you." would make it better understandable, I think.

**Comment by davitol** [comment]
> This is not related to richdocuments, is it?

Not this item is not fixable in richdocuments. I just spotted it there to ask for a better message in the warning.

**Comment by HanaGemela** [comment]
@davitol Please raise a new issue to change the message in the correct repo

**Comment by HanaGemela** [comment]
I've emailed @timar to build the final which should include https://github.com/owncloud/richdocuments/pull/326
Then it will be smoke tested before publishing

**Comment by HanaGemela** [comment]
@davitol 2.3.0 final available for smoke test https://github.com/owncloud/richdocuments/releases/tag/2.3.0
Also please test #326

**Comment by davitol** [comment]
> @davitol 2.3.0 final available for smoke test https://github.com/owncloud/richdocuments/releases/tag/2.3.0
> Also please test #326

Smoke tested and LGTM 🚢

**Comment by HanaGemela** [comment]
Published at Marketplace
