### ISSUE TITLE
Log is spotted when closing a document in collabora editor

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#325]
### Steps

1. Open a .ods file via files view
1. Made some changes and close the document (see screenshot above)
1. Check owncloud.log

### Expected result
No log should be spotted

### Actual result
Following log is spotted:

```
{"reqId":"D4uRlkp46az3nFcqFVK5","level":2,"time":"2020-03-06T13:45:28+00:00","remoteAddr":"172.19.0.1","user":"admin","app":"richdocuments","method":"POST","url":"\/apps\/richdocuments\/wopi\/files\/14_ocaw7yg7jmy3_0_0\/contents?access_token=wzNNLDOjAvP33346m8tHMOpGsePvhL82&access_token_ttl=0","message":"wopiPutFile(): mtime"}
```

**Note**: Log level: Warning (2)

### Version
ownCloud 10.4.1 and richdocuments 2.3.0 RC1

![Screen Shot 2020-03-06 at 14 48 38](https://user-images.githubusercontent.com/10596560/76089851-bc8af300-5fba-11ea-9656-5985fb6078cd.png)

~~To be investigated if it is a regression or not~~

**Comment by davitol** [comment]
Tested with oC 10.4 EE and richdocuments 2.1.2. and cannot reproduce it, so it is probably a regression

**Comment by pmaier1** [comment]
If it's just about the log entry, not a blocker. Should be fixed though, of course.

**Comment by JanAckermann** [comment]
Was a warning log entry, which should be indeed debug, fixed.
