### ISSUE TITLE
richdocuments 2.4.0

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/richdocuments#350]
### Reason

- Release needed for https://github.com/owncloud/richdocuments/issues/346
- https://github.com/owncloud/richdocuments/pull/347

### Product approval

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [ ] Generate Changelog
- [ ] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [ ] Create release branch with the format "release-$version"
- [x] Create "richdocument 2.4.0 Testplan" @davitol

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [ ] Check php version dependency in `info.xml`
- [ ] Check minimum ownCloud version dependency in `info.xml`
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [ ] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Rename QA milestone to `$version`
- [ ] Add a new 'Unreleased' section in CHANGELOG.md
- [ ] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [ ] Close the milestone
- [ ] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by HanaGemela** [comment]
I've emailed @timar asking for a new RC

**Comment by timar** [comment]
I uploaded 2.4.0RC1 signed tarball to test

**Comment by HanaGemela** [comment]
> I uploaded 2.4.0RC1 signed tarball to test

Thank you!
@davitol ready for testing

**Comment by davitol** [comment]
@HanaGemela 

Tarball is QA-ready. 

- [x] Test new licence manager
- [x] Smoke test with oC 10.5 with PHP 7.2 and PHP 7.4

Note: Tarball does not contain a Changelog file (it does not exist in the repo too)

**Comment by HanaGemela** [comment]
@timar Is that correct that the tarball doesn't contain a changelog? If so, please build the final as it passed QA.

**Comment by HanaGemela** [comment]
Final release done https://github.com/owncloud/richdocuments/releases/tag/v2.4.0

**Comment by davitol** [comment]
> Final release done https://github.com/owncloud/richdocuments/releases/tag/v2.4.0

@HanaGemela  LGTM
