### ISSUE TITLE
not previewURL ownclod9.0

### ISSUE THREAD

**Issue by shwarz13** [owncloud/richdocuments#36]
It does not show documents
create new documents , but does not show
in owncloud8.2.3 working

![- 07 04 2016 - 14 51 38](https://cloud.githubusercontent.com/assets/18259441/14350147/471f4950-fcd0-11e5-8f72-44eb4bdc76c2.png)
![- 07 04 2016 - 14 45 48](https://cloud.githubusercontent.com/assets/18259441/14350150/4ac70a5c-fcd0-11e5-8b3b-2d8960a6e083.png)

**Comment by franklines** [comment]
Did you set up loolwsd and leaflet (server side of things)? RichDocuments is just the actual plugin for OwnCloud but you still have to setup the environment.

**Comment by shwarz13** [comment]
owncloud.2.3, owncloud 9.0, loolwsd, leaflet installed on the same server.
loolwsd, leaflet used for both owncloud.
Client  (PC and browser) is the same.
owncloud8.2.3 it works.
owncloud9.0 error.
what I need to establish in the environment?

**Comment by franklines** [comment]
@shwarz13 how did you compile loolwsd and leaflet? What directory did you use for the Libreoffice source tree?

**Comment by shwarz13** [comment]
loolwsd

agree README
`    #libtoolize`
`    #aclocal`
`    #automake --add-missing`
`    #autoreconf`
`    #autoheader`

further I have collected a package for a Debian
`    #debuild --no-lintian -b`
install package

`    #loolwsd --version`
`    #1.6.0`

running
 `   #/usr/bin/loolwsd --systemplate=/opt/lool/systemplate --lotemplate=/opt/cp5.0 --childroot=/opt/lool/child-roots --numprespawns=1 `

loleaflet
I did
   ` #make`
and as in README

`    #jake build`
`    #cd plugins/draw-0.2.4`
`    #jake build  `  

LibreOffice/core
https://github.com/LibreOffice/core/tree/distro/collabora/cp-5.0

**Comment by shwarz13** [comment]
thanks. everything is ok
OC 9.0.2
