### ISSUE TITLE
richdocuments 2.5.0

### ISSUE THREAD

**Issue by pmaier1** [owncloud/richdocuments#378]
### Reason

Release needed for
- Make the Secure View licensing compatible with new license manager (since server 10.5) https://github.com/owncloud/richdocuments/pull/356
- Improved auditing capabilities for access via Collabora https://github.com/owncloud/richdocuments/pull/371
- Changes to allow opening documents explicitly with Collabora https://github.com/owncloud/richdocuments/pull/370 (needs 10.7 server, not a hard dependency)
- Bug fixes https://github.com/owncloud/richdocuments/pulls since last release

### Product approval

- [x] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [x] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "richdocument 2.5.0 Testplan" -> https://github.com/owncloud/richdocuments/issues/391
   
### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] XXX update https://confluence.owncloud.com/display/PROD/Upcoming+Releases

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [ ] ~Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com~
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] XXX update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date
- [ ] upload testplan template to https://github.com/owncloud/QA/tree/master/Server - close the testplan issue.

**Comment by ChrisEdS** [comment]
Raised the priority to p2-high. Please take care. 

Thank you BTR-Team.

**Comment by jnweiger** [comment]
The richdocuments app is built by @timar 
@ChrisEdS Do we have a github branch ready?

**Comment by jnweiger** [comment]
I have created a release branch from head of master and tagged v2.5.0RC1 there.
@timar could you please build us an RC1? Thank you!

**Comment by timar** [comment]
https://github.com/owncloud/richdocuments/releases/tag/V2.5.0RC1

**Comment by jnweiger** [comment]
Thanks, @timar 
I am afraid, I triggered you too early. We miss one patch set in RC1.
I'll make an RC2 tag. Sorry.

**Comment by jnweiger** [comment]
RC2 is ready for test:
https://github.com/owncloud/richdocuments/releases/tag/v2.5.0RC2

**Comment by jnweiger** [comment]
##Issues opened while testing

* [ ] #394 - [QA] Fullscreen presentation mode fails

**Comment by jnweiger** [comment]
passed QA with minor defects.

**Comment by pmaier1** [comment]
Would like to wait for confirmation that #394 is unrelated to the changes. Apart from that, good to go from my side :+1:

**Comment by jnweiger** [comment]
Confirmed unrelated to the current changes: I have the same issue with richdocuments-2.4.1

**Comment by jnweiger** [comment]
@timar We are happy with the release. I have tagged the same commit-id that was RC2 as a final v2.5.0 in github and made a 2.5.0 release on github with that.
If suggest you go ahead and upload that to https://marketplace.owncloud.com now. Thanks!
