### ISSUE TITLE
Cannot open docs shared from Local Storage

### ISSUE THREAD

**Issue by theheyon** [owncloud/richdocuments#385]
Hey on there!

System: Ubuntu 18.04.4 LTS + ownCloud 10.6.0 + CollaboraOnline 2.4.1
CODE:  LOOLWSD 6.4.6 / LOKit Collabora Office 6.4-23

When sharing folders with Public Links - everything goes fine until you try to share folder from **Local storage**. Then something goes wrong - getting error when you click on file:
```Collabora Online: Cannot open document. Backends provided no user object for```

Sharing any folder or document from any user folder seems to be ok.
Maybe, some trouble with missing folder owner or something like that?

Thanks for any direction to fix that =)

**Comment by theheyon** [comment]
Answering to myself =)
Figured out that same issue were fixed in NextCloud app:
https://github.com/nextcloud/richdocuments/commit/ee09fb07482e288c3245fb0948220ad6cedf3c32

So i patched _/lib/Storage.php_ a bit and its seems works...

Part of original Storage.php:
```
// Retrieve user folder for the file to be able to get relative path
$owner = $document->getOwner()->getUID();
$root = \OC::$server->getRootFolder()->getUserFolder($owner);

$ret = [];
$ret['owner'] = $document->getOwner()->getUID();
$ret['permissions'] = $share->getPermissions();
$ret['updateable'] = $document->isUpdateable();
$ret['mimetype'] = $document->getMimeType();
$ret['path'] = $root->getRelativePath($document->getPath());
$ret['name'] = $document->getName();
$ret['fileid'] = $document->getId();
$ret['instanceid'] = \OC::$server->getConfig()->getSystemValue('instanceid');
$ret['version'] = '0'; // latest
$ret['sessionid'] = '0'; // default shared session

return $ret;
```

Patched:
```
// Retrieve user folder for the file to be able to get relative path

$owner = $share->getShareOwner();
if (is_null($owner)) {
    $owner = $document->getOwner()->getUID();
}
$root = \OC::$server->getRootFolder()->getUserFolder($owner);

$ret = [];
$ret['owner'] = $owner;
$ret['permissions'] = $share->getPermissions();
$ret['updateable'] = $document->isUpdateable();
$ret['mimetype'] = $document->getMimeType();
$ret['path'] = $root->getRelativePath($document->getPath());
$ret['name'] = $document->getName();
$ret['fileid'] = $document->getId();
$ret['instanceid'] = \OC::$server->getConfig()->getSystemValue('instanceid');
$ret['version'] = '0'; // latest
$ret['sessionid'] = '0'; // default shared session

return $ret;
```

Im really sorry, but im a newbie here and dont know how to contribute correctly (
Anybody help me pls and tell, if i have to close this issue

**Comment by micbar** [comment]
@theheyon thanks for opening this!

@mrow4a Can you give guidance?
