### ISSUE TITLE
[QA] Use different icons f.ex. Collabora and Rename

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/richdocuments#389]
### Expected behaviour
Icons should be different for different operations

### Actual behaviour
The icon for open in f.ex. Collabora and Rename is the same

<img width="208" alt="Screenshot 2021-03-26 at 16 48 14" src="https://user-images.githubusercontent.com/33026403/112659247-7a964e80-8e54-11eb-8937-a266ba818188.png">

### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.7.0 RC2

**Comment by JanAckermann** [comment]
Not sure where we can get those icons

**Comment by jnweiger** [comment]
Seen with richdocuments 2.5.0 RC2:
*click the three dots on a PDF file:
![image](https://user-images.githubusercontent.com/1108546/116949716-5a438600-ac83-11eb-84ca-f4a268a7a54e.png)

- Still dupicate icon.
- Icon missing on "Favorite" -- which should be renamed to "PDF-Viewer"

**Comment by JanAckermann** [comment]
@jnweiger Like always, update files_pdfviewer and the 'Favorite' aka Open in PDF Viewer will be fine
