### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rtjdamen** [owncloud/richdocuments#39]
Hi Guys,

i would love to test this plugin. I downloaded the Code VM and i did fill in the ip of that vm into the wopi client field. After browsing to the plugin i get this error. any idea? 

![image](https://cloud.githubusercontent.com/assets/18336678/14384506/bd0881a6-fd9b-11e5-92f5-31b7b997f5e1.png)

**Comment by franklines** [comment]
You have to add the IP to the config file. Login as root and make the needed changes.

"Want to enter as the root user in the virtual machine? Enter with: root / skew25.kiwis"

# vi /srv/www/htdocs/owncloud/config/config.php

```
'trusted_domains' =>
array (
   'x.x.x.x',
   ),
```

You should be able to login using the following credentials: admin:admin

**Comment by timar** [comment]
Closing, because discussion did not go any further.
