### ISSUE TITLE
[QA] Chooser popup on PDF offers "Favorite"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#395]
Seen with richdocuments 2.5.0 RC2 on 10.7.0 with also files_pdfviewer enabled

![image](https://user-images.githubusercontent.com/1108546/116949984-fff6f500-ac83-11eb-9bef-b3067762a69a.png)

Expected behaviour: Show "PDF-Viewer" instead of "Favorite"

**Comment by jnweiger** [comment]
@JanAckermann DeJaVu? https://github.com/owncloud/richdocuments/issues/388

**Comment by JanAckermann** [comment]
@jnweiger Please bump the version of PDF Viewer to the latest one

**Comment by pmaier1** [comment]
Already fixed? If not, please move into the right repo and take care.

**Comment by JanAckermann** [comment]
@pmaier1 @jnweiger Fixed long time ago, but still pops-up consistently
