### ISSUE TITLE
Release richdocuments 2.6.0 

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/richdocuments#401]
# Release 2.6.0

## Reasons
- Enhancement: Allow setting default open action with secure-view enforced session for supported documents https://github.com/owncloud/richdocuments/pull/400
- Enhancement: Enable comments on PDFs https://github.com/owncloud/richdocuments/pull/404
- Enhancement: Use app icon for Open in Collabora action  https://github.com/owncloud/richdocuments/pull/406 
- Bugfix: Don't log warning message on PUT in favour of debug #407 
- Bugfix: Prevent documents with tabs in filenames / or any other invalid chars from being created https://github.com/owncloud/enterprise/issues/4628 https://github.com/owncloud/richdocuments/pull/418

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [ ] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> #416 
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+differences+in+release+process) applies, and adapt this checklist.  release build and upload by Collabora!

### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build
- [x] build done by Collabora
- [x] Check version number in info.xml
- [x] check Changelog 
 -> 2.6.0-RC2unsigned with changlog update, and fix for #417

#### Beta/RC

- [x] Manual explorative testing:
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Send Go Ahead to Collabora

### Publishing

- [x] Collabora uploads tarball to marketplace

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by JanAckermann** [comment]
Beta release, no QA needed

**Comment by jnweiger** [comment]
Beta1 built. Not uploaded to github.

**Comment by jnweiger** [comment]
Beta1 built. Not uploaded to github.

**Comment by micbar** [comment]
ok, not finished with beta. Needs proper release.

New stuff from master should be included.

**Comment by mmattel** [comment]
Q: will this release go public?

**Comment by JanAckermann** [comment]
A: yes, but it is still in dev, as @micbar approves, he will move it to DEV done, rc needed

**Comment by jnweiger** [comment]
2.6.0-beta1 is not signed, (says server 10.8.0-beta1) -- no idea why...

**Comment by JanAckermann** [comment]
@jnweiger needs to be signed by collabora not owncloud, but we still need customer feedback :/

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] https://github.com/owncloud/richdocuments/issues/417

**Comment by jnweiger** [comment]
@timar 
I've built a https://github.com/owncloud/richdocuments/releases/download/v2.6.0RC2/richdocuments-2.6.0RC2unsigned.tar.gz
With updated changelog and the fix for #417, please review and replace with a signed one, if all is well.

**Comment by timar** [comment]
> @timar
> I've built a https://github.com/owncloud/richdocuments/releases/download/v2.6.0RC2/richdocuments-2.6.0RC2unsigned.tar.gz
> With updated changelog and the fix for #417, please review and replace with a signed one, if all is well.

@jnweiger done.

**Comment by jnweiger** [comment]
QA passed. Happy to release.

**Comment by timar** [comment]
> QA passed. Happy to release.

I made the release on GitHub and Marketplace. Thanks!

**Comment by jnweiger** [comment]
Release done.
