### ISSUE TITLE
richdocuments 2.7.0

### ISSUE THREAD

**Issue by pmaier1** [owncloud/richdocuments#427]
# Release 2.7.0

## Reasons
- ownCloud Web compatibility https://github.com/owncloud/richdocuments/pull/423
- Support for Draw https://github.com/owncloud/richdocuments/pull/436
- Fix broken upload https://github.com/owncloud/richdocuments/pull/437

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> https://github.com/owncloud/richdocuments/issues/440
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] XXX check if [Non-normal Release Process](https://confluence.owncloud.com/x/h4JK) applies, and adapt this checklist.  release build and upload by Collabora!

### Documentation

- [x] Update oC Web documentation on how to use Collabora Online with oC Classic backend (https://owncloud.dev/clients/web/deployments/oc10-app/#integrate-owncloud-classic-features-in-owncloud-web)
https://github.com/owncloud/web/pull/6282

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally
- [x] Include in oC Web release communication

### Build
- [x] build done by Collabora
- [x] Check version number in info.xml
- [x] check Changelog 

#### Beta/RC

- [x] Manual explorative testing:
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Send Go Ahead to Collabora

### Publishing

- [x] Collabora uploads tarball to marketplace

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by pmaier1** [comment]
https://github.com/owncloud/richdocuments/pull/423 is about to be merged. Starting the release process.

One more task for the release: Update oC Web documentation on how to use Collabora Online with oC Classic backend (https://owncloud.dev/clients/web/deployments/oc10-app/#integrate-owncloud-classic-features-in-owncloud-web)

cc @jnweiger @merttumer @timar

**Comment by jnweiger** [comment]
I believe we are ready to roll a release here. 
I've updated the CHANGELOG.md, tagged v2.7.0-rc1. 
@timar Please doublecheck that changelog and build a signed tar and attach to https://github.com/owncloud/richdocuments/releases/tag/v2.7.0-rc1

**Comment by pmaier1** [comment]
If possible, let's include this in the release https://github.com/owncloud/richdocuments/pull/436

**Comment by JanAckermann** [comment]
Added https://github.com/owncloud/richdocuments/pull/437

**Comment by jnweiger** [comment]
Build (a not signed) RC2 including #436 and #347: https://github.com/owncloud/richdocuments/releases/tag/v2.7.0-rc2

**Comment by jnweiger** [comment]
## Issues seen while testing 2.7.0 RC2

* [ ] https://github.com/owncloud/richdocuments/issues/439
* [ ]

**Comment by jnweiger** [comment]
Release done with nonblocking issues.
