### ISSUE TITLE
Can't install it says missing file

### ISSUE THREAD

**Issue by KiraNavarro** [owncloud/richdocuments#44]
Trying to install this, I got stuck on the second step, I get this:

"error: failed to stat /owncloud/apps/richdocuments/owncloud-collaborate-online.spec: No such file or directory"

I looked in there but I just found this file collabora-online.spec.in ,  should I just remove the .in from this file and try again the rpmbuild?

**Comment by franklines** [comment]
Try creating a tarball version, worked for me.

**Comment by timar** [comment]
Run `make dist`, it creates the spec file from spec.in file.
