### ISSUE TITLE
Secureview works without EE License

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#442]
Seen with ownCloud 10.9.1 and richdocuemnts 2.7.0 RC2

* start without any enterprise apps and no license installed.
* enable richdocuments app
* `occ config:app:set richdocuments secure_view_option --value true` 
* share with a user, 
* check the default sharing settings. Secureview is chosen. BAD
* admin visits additional settings. He can switch on and off securevie in the collabora section. BAD.

Expected behaviour:
*  secure view only works with an active enterprise license. The occ command should not enable secureview without  license.

**Comment by jnweiger** [comment]
Same with richtdocuments 2.5.0 and 2.6.0 on server 10.9.1

**Comment by pmaier1** [comment]
Actually we switched the license check to the new licensing mechanism that was introduced with Server 10.5. Ref. https://github.com/owncloud/richdocuments/issues/346. This needs another look from dev.

**Comment by mrow4a** [comment]
@pmaier1 @jnweiger related issue https://github.com/owncloud/enterprise/issues/4143
