### ISSUE TITLE
New Diagram is missing from the "Office" app switcher

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#444]
Seen with ownCloud 10.9.1 and richdocuemnts 2.7.0 RC2

* install richdocuments app
* click the 'Office' icon in the app switcher
![image](https://user-images.githubusercontent.com/1108546/150012383-5f355345-8495-476c-bcf4-0226a2b19e46.png)

* A view opens, with all existing office documents and a sidebar to create new documents 
![image](https://user-images.githubusercontent.com/1108546/150012497-6c47d8f3-9634-44ac-9713-c41caca35529.png)

"New Diagram" is missing in this view.

Expected behaviour:
* consistency with the '+' drop-down in the files view. There we have 'Diagram'

**Comment by mrow4a** [comment]
same as in https://github.com/owncloud/richdocuments/issues/445#issuecomment-1016761295 . We might need to check with Collabora [extensions](https://github.com/owncloud/richdocuments/blob/master/lib/Storage.php#L33-L71) that are currently supported 

Diagram not available with "Files" and "Office"
<img width="762" alt="Screenshot 2022-01-19 at 20 08 49" src="https://user-images.githubusercontent.com/13368647/150198092-75466cd3-4b1f-4fcc-9685-1a9558428ff5.png">
