### ISSUE TITLE
App switcher in new web UI shows collabora with a nameless default puzzle icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#446]
Seen with ownCloud 10.9.1 and richdocuemnts 2.7.0 RC2 using web-4.9.0

![image](https://user-images.githubusercontent.com/1108546/150014847-7883c982-85ac-4fec-8a5d-2869e65104f5.png)
The icon indicated by the mousepointer switches to the collabora view.

Expected behaviour:
* The name Collabora should be shown under the icon
* The icon should be a more typical Collabora icon

**Comment by jnweiger** [comment]
@pmaier1 can we release with this defect?

**Comment by pmaier1** [comment]
This is expected as we simply load all entries from the oC 10 application switcher to the oC Web application switcher to make them available there. For this we use the puzzle icon for some reason.

> @pmaier1 can we release with this defect?

Yes
