### ISSUE TITLE
Upload button overlaps with a document icon in the second row

### ISSUE THREAD

**Issue by timar** [owncloud/richdocuments#468]
![image](https://user-images.githubusercontent.com/290614/167621171-f531bd7d-917d-4c69-a10a-8e3e11377614.png)
richdocuments 2.7.0

**Comment by SakshiT25** [comment]
hi, if this issue is still open. I would like to work on it.
thank you.

**Comment by ChrisEdS** [comment]
Hello @SakshiT25, the issue is still open, I just saw the issue in the product and wanted to open a new bug report. It would be awesome if you can work on a fix.

**Comment by ChrisEdS** [comment]
I think the solution can be to set `display: inline-table;` here
https://github.com/owncloud/richdocuments/blob/7ce3bab30a6f68b398a1ef3fe72b2c1916cac783/css/style.css#L23
