### ISSUE TITLE
Richdocuments Release 2.8.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/richdocuments#471]
### Reason

- [#456](https://github.com/owncloud/richdocuments/pull/456) - web: add Drawing filetype and add it to + menu
- [#467](https://github.com/owncloud/richdocuments/pull/467) - Set appropriate icon for web
- [#462](https://github.com/owncloud/richdocuments/pull/462) - Adjust 'if' conditionals that were reported by phpstan
- [#457](https://github.com/owncloud/richdocuments/pull/457) - typo fix (templates/documents.php)
- [#455](https://github.com/owncloud/richdocuments/pull/455) - ensure ODG Drawing compatibility across integration
- [#454](https://github.com/owncloud/richdocuments/pull/454) - Change Richdocuments app name to Collabora Online
- [#451](https://github.com/owncloud/richdocuments/pull/451) - disable secure view js and settings when not available
- [#468](https://github.com/owncloud/richdocuments/pull/468) - Upload button overlaps with a document icon in the second row
- [#486](https://github.com/owncloud/richdocuments/pull/486) - E5515 feature/wopi locks

----
@jnweiger Do we need a release of existing changes/fixes?
PR #470 adjusts a small piece of code because of Guzzle7-related changes in core for core 10.11. After merging that, the `master` branch will require core 10.11.

So, if there is anything needed to release to fix/improve the app with core 10.10 then the release should be done before we merge #470 

### Product approval 

- [x] Verify transifex commits are in master: If a toplevel folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...
- [x] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) ->  https://github.com/owncloud/richdocuments/issues/488
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new .

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch from here:
- [ ] Bump version in `appinfo/info.xml` (no version suffix)
- [ ] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [ ] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [ ] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [ ] `git tag -s v${version}-rc.1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [ ] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [ ] Upload as Github release using changelog entries
- [ ] Test and document in testplan + manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [ ] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [ ] Do changelog tests
    - [ ] Do regression tests
    - [ ] PHP 7.3 compatibility (`HCLOUD_SERVER_IMAGE=debian-10 oc10.sh ...`)
    - [ ] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [ ] Rename last RC tarball to final
- [ ] Create github tag for final `v${version}` on release branch
- [ ] Upload as Github release using changelog entries

### Publishing

- [ ] Upload tarball to marketplace (see handbook in confluence for details)
- [ ] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [ ] Send mail to release-coordination with link to this ticket and to the changelog
- [ ] Copy email to rocket chat `#updates` channel

### Post-release

- [ ] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [ ] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [ ] Rename QA milestone to `$version` and close the milestone
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [ ] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [ ] Close the testplan issue

**Comment by phil-davis** [comment]
It looks like these PRs are in master since https://github.com/owncloud/richdocuments/releases/tag/v2.7.0 was released on 2022-01-20:

#451 disable secure view js and settings when not available
#454 Change Richdocuments app name to Collabora Online
#455 ensure ODG Drawing compatibility across integration
#456 web: add Drawing filetype and add it to + menu
#457 typo fix
#462 Adjust 'if' conditionals that were reported by phpstan
#467 Set appropriate icon for web

should there be a release done "now" and tested against ownCloud core 10.10?

@pmaier1 ?

**Comment by jnweiger** [comment]
I guess, in principle it is a good idea to release twice here. 
2.8.0 with the accumulated patches before guzzle.
2.9.0 with the above and with guzzle patches.

That way customers who cannot immediately jump to core 10.11 can still get the accumulated updates in richdocuments 2.8.0

Question that I cannot answer: is it worth the effort?

**Comment by phil-davis** [comment]
> Question that I cannot answer: is it worth the effort?

My opinion is yes, it is worth the effort. But I am not running the show!

**Comment by timar** [comment]
I'm happy to create a signed package for Marketplace, when you make a final release tag.

**Comment by jnweiger** [comment]
Prepared release-2.8.0 branch for this.

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] https://github.com/owncloud/core/issues/40687
* [ ]

**Comment by phil-davis** [comment]
Note: there is also code that is updated/added that has correct Symfony calls to work with Symfony4 (now) and Symfony5 (coming with core 10.13). It would be good to get this release done and out before 10.13.

**Comment by jnweiger** [comment]
Add @mrow4a 's #493 here too?

**Comment by mrow4a** [comment]
@jnweiger yes

**Comment by jnweiger** [comment]
3.0.0 was inofficially done (without approval from @timar ) 
We'll followup with a 3.1.0

**Comment by mrow4a** [comment]
we already have richdocuments 4.0.0 released
