### ISSUE TITLE
Creating new document works, opening existing one fails

### ISSUE THREAD

**Issue by linuxrrze** [owncloud/richdocuments#49]
I'm running this setup:

- owncloud 9.0.1
- latest libreoffice (git)
- latest libreoffice-online (git)
- latest richdocuments (git)
(Ubuntu 16.04  x86_64)

When creating new documents via "Collabora Online" -> "Create ..."
richdocuments works as expected, however trying to open an existing
Document fails.

The redirect to richdocuments works:

http://looc.local.de/owncloud/index.php/apps/richdocuments/index#43

But in the content area I get:

Not Found

The requested URL /owncloud/index.php/apps/richdocuments/undefinedWOPISrc=http://looc.local.de/owncloud/index.php/apps/richdocuments/wopi/files/43&title=New Document.odt&closebutton=1 was not found on this server.

After some research I found a *very dirty* hack, to pass the right settings
(by statically using the URL, that should be provided by parsing the xml
of loolwsd in http://looc.local.de:9980/hosting/discovery):

So i Modified apps/richdocuments/js/documents.js:

   // var urlsrc = $('li[data-id='+ documentsMain.fileId +']>a').attr('urlsrc') +
   var urlsrc = "http://looc.local.de:9980/loleaflet/1.6.2/loleaflet.html?" +
                   "WOPISrc=" + wopisrc +
                   "&title=" + encodeURIComponent(title) +
                   "&closebutton=1";

Somehow the "urlsrc" attribute (and maybe more) seems to miss.

**Comment by shwarz13** [comment]
owncloud9.0.0 Same problem "Not found"
in owncloud8.2.3, no problem, open page server "loolwsd"

**Comment by guidtz** [comment]
Hello,

  same problem so I cannot create new document. Document is created in owncloud but no libreoffice editor is appear. I have the waiting wheel and nothing else.

Regards

**Comment by justlomo** [comment]
linuxrrze
How did you compile and run loolwsd and loleaflet?
I got problem when I compile loleaflet.
npm -g jake << error
Can you tell me about it please?

**Comment by guidtz** [comment]
This is a cut of my compile procedure
`The server side component.

cd online/loolwsd

libtoolize
aclocal
automake --add-missing
autoreconf
autoheader

MASTER=/home/admin/libreoffice

./configure --enable-silent-rules --disable-ssl --with-lokit-path=${MASTER}/include --with-lo-path=${MASTER}/instdir

make

sudo mkdir -p /usr/local/var/cache/loolwsd
sudo chown `whoami` /usr/local/var/cache/loolwsd
sudo ln -s /home/admin/online/loolwsd/etc/ /etc/loolwsd

make run &



The client side component

cd /home/admin/online/loleaflet

# apt-get install nodejs-legacy npm
# npm install -g jake
cd /home/admin/online/loleaflet
# npn install

As user :
$ jake build
$ cd plugins/draw-0.2.4
$ jake build
`

On debian 8 server

**Comment by timar** [comment]
The object not found error has been fixed, see https://github.com/owncloud/richdocuments/pull/58

**Comment by guidtz** [comment]
Hello, I update owncloud and rochdocument apps but I haven't got task bar :-( How can I debug this ?

Thanks
