### ISSUE TITLE
WebUI acceptance tests are failing in Nightly in BeforeScenario

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/richdocuments#490]
Acceptance tests are failing in CI with
```
 ┌─ @BeforeScenario @webUI # SecureViewContext::before()
  │
  ╳  Fatal error: Typed property FeatureContext::$occLastCode must not be accessed before initialization (Behat\Testwork\Call\Exception\FatalThrowableError)
  │
```

Recently we did a big refactoring in core https://github.com/owncloud/core/pull/40754/files, so this might be one of the reasons behind this failure or it could be something else. Find out the issue and fix it.

Build link: https://drone.owncloud.com/owncloud/richdocuments/2396/14/12

**Comment by SwikritiT** [comment]
This issue and this issue https://github.com/owncloud/user_ldap/issues/784 might have a similar fix

**Comment by SagarGi** [comment]
Nightly build passing for this app so closing this issue.
