### ISSUE TITLE
How to Input Chinese in CODE

### ISSUE THREAD

**Issue by remarklin** [owncloud/richdocuments#5]
when I try Chinese typing, it cant input to file by Microsoft IME or Linux SCIM...
I tried copy/paste from a notepad to screen , it works fine

so maybe it's a problem in PC's?(I haven't tried a tablet with owncloud)

**Comment by timar** [comment]
It is possible to input Chinese in CODE since this update:
https://www.collaboraoffice.com/community-news/code-2-0-updates-2/
