### ISSUE TITLE
richdocuments 4.0.0 release

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#501]
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://confluence.owncloud.com/display/OG/Releasing+Apps

### Reason

- Release needed for
   - #498  
   - #497 
  - #496
  - #494 
  - #493 
  - #464 
  - [#493](https://github.com/owncloud/richdocuments/pull/493) - make sure to retrieve correct supershare based on current dir context
  - [#492](https://github.com/owncloud/richdocuments/pull/492) - Remove Symfony event dispatch from ignoreErrors
  - [#456](https://github.com/owncloud/richdocuments/pull/456) - web: add Drawing filetype and add it to + menu
  - [#467](https://github.com/owncloud/richdocuments/pull/467) - Set appropriate icon for web
  - [#462](https://github.com/owncloud/richdocuments/pull/462) - Adjust 'if' conditionals that were reported by phpstan
  - [#457](https://github.com/owncloud/richdocuments/pull/457) - typo fix (templates/documents.php)
  - [#455](https://github.com/owncloud/richdocuments/pull/455) - ensure ODG Drawing compatibility across integration
  - [#454](https://github.com/owncloud/richdocuments/pull/454) - Change Richdocuments app name to Collabora Online
  - [#451](https://github.com/owncloud/richdocuments/pull/451) - disable secure view js and settings when not available
  - [#468](https://github.com/owncloud/richdocuments/pull/468) - Upload button overlaps with a document icon in the second row
  - [#486](https://github.com/owncloud/richdocuments/pull/486) - E5515 feature/wopi locks

### Product approval 

- [ ] Verify transifex commits (enterprise should update weekly, others daily): If folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...
- [ ] Ping ProductManagement to check `info.xml` description and screenshot

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "4.0.0 Testplan" --> #500  ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core))
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [ ] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new .

### Marketing

- [ ] Ping @owncloud/marketing
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [ ] Request a screenshot if the app is new or changed fundamentally

### Build

All actions to be done on the release branch (`git pull; git checkout -b release-x.x.x`) from here:
- [x] Bump version in `appinfo/info.xml` (no version suffix)
- [x] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] `git tag -s v${version}-rc.1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [ ] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] Watch out for untranslated strings when locale is de oder de_DE.
    - [ ] PHP 7.3 compatibility (`HCLOUD_SERVER_IMAGE=debian-10 OC10_VERSION=10.11 oc10.sh ...`)
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook in confluence for details)
- [ ] Publish tarball for customers  - [old 10](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Enterprise%2FownCloud-10), [old 10.0](https://customer.owncloud.com/owncloud/index.php/apps/files/?dir=%2FownCloud-Server%2FownCloud-10.0) and [new portal](https://portal.owncloud.com/apps/files/?dir=/Portal%20Data/All%20Account%20Data/ownCloud%20Enterprise%20Resources%20Data/Server&fileid=5661) (see [handbook](https://confluence.owncloud.com/display/OG/Releasing+Apps) for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [x] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by jnweiger** [comment]
https://github.com/owncloud/richdocuments/releases/download/v4.0.0-rc.1/richdocuments-4.0.0-rc.1.tar.gz

**Comment by jnweiger** [comment]
richdocuments seems to be completely independant of guzzle now:
git diff ef8038897f69ed5baa5b689a67dc5eba10b1bc71..89c95a0a2e33d621fd7ef30636f859773d44eef7

@pako81 I'd like to deviate from the general rule of oc minversion 10.11 here, and make it oc minversion 10.9.1 instead to keep customers happy, that did not update yet.

**Comment by jnweiger** [comment]
This includes #498 Federated shares support v1

https://github.com/owncloud/richdocuments/releases/download/v4.0.0-rc.3/richdocuments-4.0.0-rc.3.tar.gz

**Comment by jnweiger** [comment]
## Security issues seen
* [ ] https://github.com/owncloud/richdocuments/security/dependabot     0 Crit, 1 High

**Comment by mrow4a** [comment]
@jnweiger if we could fit also bugfixes to admin panel , along that zotero integration in the release + qa , would be amazing https://github.com/owncloud/richdocuments/pull/505

**Comment by mrow4a** [comment]
@jnweiger as discussed https://github.com/owncloud/richdocuments/pull/507 targeting release-4.0.0

**Comment by mrow4a** [comment]
@jnweiger any info on release here?

**Comment by mrow4a** [comment]
@jnweiger any info on release here?

**Comment by jnweiger** [comment]
The release-4.0.0 branch is outdated. Merging back to master without release, to get hings going again.
I'll create a new release-4.0.0 branch after all pending PRs in master are sorted out.
The next release candidate will still be 4.0.0-rc.4 then.

**Comment by jnweiger** [comment]
New release-4.0.0 branch is created: We have RC 4

https://github.com/owncloud/richdocuments/releases/tag/v4.0.0-rc.4

**Comment by jnweiger** [comment]
QA passed.
Unsigned 4.0.0 final uploaded to github as prerelease.
Handing over to @timar for signing the release and pushing to marketplace, please.

**Comment by jnweiger** [comment]
## Issues seen while testing
* [ ] #515
* [ ] #514 -> **RELEASE BLOCKER**

**Comment by jnweiger** [comment]
## Ready for QA
* https://github.com/owncloud/richdocuments/releases/download/v4.0.0-rc.5/richdocuments-4.0.0-rc.5.tar.gz

**Comment by timar** [comment]
> ## Ready for QA
> * https://github.com/owncloud/richdocuments/releases/download/v4.0.0-rc.5/richdocuments-4.0.0-rc.5.tar.gz

It's OK from my side.
