### ISSUE TITLE
Need help with merging  lib/Controller/DocumentController.php

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#502]
Back in August 2022 we had merged #475 into release-3.0.1, but never managed to really do a release. Sorry for this.

https://github.com/owncloud/richdocuments/compare/master...release-3.0.1

Now master is way ahead, and I'd like release version 3.1.0 (jumping foraward one minor version, to leave confusion about patchlevel releases that did not happen behind)
I've preliminary merged most changes into 
https://github.com/owncloud/richdocuments/commits/release-3.1.0
The last two commits were picked from the change set that was only in 3.0.1 but not in master.

There is one more unmergeable changeset for lib/Controller/DocumentController.php in the release-3.0.1 branch -- appended as a patch-2-4.txt below.

[patch-2-4.txt](https://github.com/owncloud/richdocuments/files/12030477/patch-2-4.txt)

@mrow4a could you please review what should be merged into the next release? Maybe I already have pulled too much outdated code  into the new release-3.1.0 branch?

**Comment by mrow4a** [comment]
decided to create 4.0.0
