### ISSUE TITLE
SSL: certificate subject name 'localhost' does not match target host 

### ISSUE THREAD

**Issue by guidtz** [owncloud/richdocuments#51]
Hello, 

I have this error if I parameter richdocuments with ssl url 

> Collabora Online unknown error: cURL error 51: SSL: certificate subject name 'localhost' does not match target host name 'libreoffice.mydomain.com'

I done that :  
`cat ca-chain.cert.pem >> www/resources/config/ca-bundle.crt`

Thanks for you're help

**Comment by timar** [comment]
Why don't you generate a certificate, that matches your target host name? I used this tutorial:
https://jamielinux.com/docs/openssl-certificate-authority/index.html

**Comment by guidtz** [comment]
Hello,

 I generate my own certificate and now I haven't got error. Very good I can continue to test this good apps.

Regars

**Comment by joeyjy** [comment]
Hello @guidtz 

I meet the same problem when I use self-signed crt, but I only got such an error message 'Collabora Online unknown error: cURL error 51: See http://curl.haxx.se/libcurl/c/libcurl-errors.html' without detail information.
How do you generate your onw certificate?
