### ISSUE TITLE
[QA] federated sharing with new web UI fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#513]
seen with core 10.13.1 and richdocuments 4.0.0-rc.4

* Setup federated sharing between two owncloud instances (both with same software versions).
* users on both instances can collaboratively edit the same document. OK
   (The receiver of the federated share sees that his browser was redirected to the origin owncloud instance)
* enable new web UI on one of the machines. The user can edit a local office document in richdocuments. OK
* using the new web UI fails to edit a file recieved via federated share. BAD
   (The receiver of the federated share sees that his browser *remains* on his owncloud instance)

![grafik](https://github.com/owncloud/richdocuments/assets/1108546/fd75519f-5ce0-4545-a021-e23bb40b3d33)
----
![grafik](https://github.com/owncloud/richdocuments/assets/1108546/2cf85cf6-3cc7-4ef9-b4ab-1c6f04090019)

**Comment by mrow4a** [comment]
Yes, new frontend is not supported currently.

**Comment by cdamken** [comment]
after talking with the PM @tbsbdr he said: Wont fix
