### ISSUE TITLE
Upload button overlaps with document icon

### ISSUE THREAD

**Issue by timar** [owncloud/richdocuments#515]
![image](https://github.com/owncloud/richdocuments/assets/290614/e1070f58-3629-4ff7-994d-16e83f83e1ec)
The reason: "New Drawing" button was added recently.

**Comment by timar** [comment]
After the fix:
![image](https://github.com/owncloud/richdocuments/assets/290614/ccdc3d85-84e4-4f40-bcdf-de4f2c2cd722)

**Comment by jnweiger** [comment]
This seems somewhat browser dependant. I get a wraparound only fter the second rows in firefox. But #516 is definitly an improvement. 
I believe @ChrisEdS also had different fix for something very similar, that is also went into the 4.0.0 release. Cannot find that PR right now.
