### ISSUE TITLE
Richdocuments complains about incorrect zotero api key

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#527]
Seen with richdocuments-4.1.0-rc.1

* do not configure anything about zotero in the settings.
* just connect to a collabora server, as with 4.0.0 and before.
* open any document in collabora, text, spreadsheet, presentation, drawing, or pdf: A message appears near the bottom. The zoero api key is incorrect. BAD

![grafik](https://github.com/owncloud/richdocuments/assets/1108546/e1b9e147-241d-4494-bae9-5562f23949a3)

Expected behaviour:
* this message should only appear, if  zotero is enabled.

**Comment by mrow4a** [comment]
hmm weird, will check

**Comment by jnweiger** [comment]
Fixed in #529 - there is no message, when a zotero key was never entered or deleted by saving empty. OK
The message still appears, when a random string was entered as zotero key. OK

**Comment by mrow4a** [comment]
@jnweiger cannot reproduce. you need [release of Collabora Online 22.05.10](https://www.collaboraoffice.com/collabora-online-22-05-release-notes/) at minimum. I also added now hint in the settings for this

<img width="989" alt="Screenshot 2023-11-10 at 08 18 12" src="https://github.com/owncloud/richdocuments/assets/13368647/27b09950-0d00-47e0-b4c0-9eafa5705f28">

**Comment by jnweiger** [comment]
Ok. So I cannot test this with the old unmaintained Collabora server that I have.

**Comment by mrow4a** [comment]
The good part is that if key is not specified it works as before. Rest, if this is a case, we need to entrust my local Zotero testing.

**Comment by jnweiger** [comment]
I've succeeded with the docker-compose setup from https://github.com/ValentinKruegl/owncloud_collabora
and I've created a zotero api key for myself at https://www.zotero.org/juergen.weigert/library

The collabora server has commit.history.core": "https://git.libreoffice.org/core/+log/cp-23.05.5-4",

But the same problem still exists: I always get 
![image](https://github.com/owncloud/richdocuments/assets/1108546/0ce0b850-9d76-4ab3-bd93-3da13cbb0af2)

a) before I enter a key,
b) after I enter the correct key
c) when I enter a wrong key.

So I am afraid, that now all users will get this message, as soon as the admin enables zotero.

**Comment by jnweiger** [comment]
One issue is now identified, that fooled me probably most of the time:
The Save button does not save what was pasted.

* generate a zotero key. Or copy paste something else for demonstrtion purposes. I am using the text "Bibliography and Citation" from the settings page.
* copy paste the key into Settings Personal Additional.

![image](https://github.com/owncloud/richdocuments/assets/1108546/b7e094a0-e9d3-481b-9606-ff0704cc7d5b)
----
![image](https://github.com/owncloud/richdocuments/assets/1108546/5bb5629e-10b1-4963-a865-eceeb3339bb3)

* note, how the Save button has exactly the same gray, before and after pasting. BAD
* Hitting Save does nothing. BAD.
   As a User, one might assume, there is by design no feedback after saving. We have it that way in other places.
* Type 'X', see how the Save button changes to a darker gray. OK

![image](https://github.com/owncloud/richdocuments/assets/1108546/8dfe48d7-3908-47b5-8d36-f2eafbfdd925)
----

* Now a click on the Save button is confirmed with a nice green 'Saved!' message. OK.

![image](https://github.com/owncloud/richdocuments/assets/1108546/2b1f2577-627e-4c40-900a-0f8becc87763)
----

For real world usage, the instruction to save needs to be:
* Paste the zotero api key, then type something, then erase what you typed, then hit Save.

**Comment by jnweiger** [comment]
fixed in 4.1.0-rc.2
