### ISSUE TITLE
Large number of files

### ISSUE THREAD

**Issue by hawatius** [owncloud/richdocuments#53]
If the user has a large number of files when opening the file "was not found on this server." the logs can be seen that there is no reference to libreoffice-online. If the file is not enough everything works well. What could be the problem?

richdocuments 0.15.2
owncloud 8.2.5
libreoffice latest version
libreoffice-online latest version

**Comment by timar** [comment]
Thanks for the bug report, I can confirm the bug. Investigating...

**Comment by timar** [comment]
This bug has been fixed already.
See https://github.com/owncloud/richdocuments/pull/58
