### ISSUE TITLE
Release richdocuments 4.2.0

### ISSUE THREAD

**Issue by pako81** [owncloud/richdocuments#536]
Using issue template from /home/testy/src/github/owncloud/QA/tools/release/templates/server_app_release_template.md
This is the server app release template, please copy the part below in a new ticket.
For instructions around app releases, see https://confluence.owncloud.com/display/OG/Releasing+Apps

### Reason

- #535
- https://github.com/owncloud/core/pull/41161
- https://github.com/owncloud/enterprise/issues/6349

### Product approval 

- [x] Verify transifex commits (enterprise should update weekly, others daily): If folder `l10n` exists, then `git log` should show '[tx] updated from transifex` ...
- [x] Ping ProductManagement to check `info.xml` description and screenshot

### QA

- [x] Create **QA** Milestone and set the description to $version
- [ ] Move tickets from milestone `development` to `qa` (testplan and tickets mentioned in release ticket)
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server) or [Enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) -> #539 
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.
- [x] check if [Non-normal Release Process](https://confluence.owncloud.com/display/OG/Apps+with+special+release+process) applies, and adapt this checklist.

### Documentation

- [x] Changes in the docs needed? If so create issue in https://github.com/owncloud/docs-server/issues/new

### Build

All actions to be done on the release branch (`git pull; git checkout -b release-x.x.x`) from here:
- [x] Bump version in `appinfo/info.xml` (no version suffix)
- [x] Check php version dependency and minimum ownCloud version dependency in `appinfo/info.xml`
- [x] Bump "sonar.projectVersion=" in `sonar-project.properties` (no version suffix)
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] `git tag -s v${version}-rc.1` on release branch (see https://confluence.owncloud.com/display/EN/Product+Owners+List)
- [x] Build and sign RC tarball from github tag `v${version}-rc.1` (see handbook for how to build)
- [ ] Check buildlog for security reports
- [x] Check github security tab dependabot reports
    - [ ] -> if critical or high entries are reported: open a release blocker issue.
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan + manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period
    - [x] Add section "Changlog Testing" using github releases text or CHANGELOG.md from release branch
    - [x] Do changelog tests
    - [x] Do regression tests
    - [x] Watch out for untranslated strings when locale is de oder de_DE.
    - [ ] PHP 7.3 compatibility (`HCLOUD_SERVER_IMAGE=debian-10 OC10_VERSION=10.11 oc10.sh ...`)
    - [x] => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Ping Collabora -> Andras Timar

### Post-release

- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with description "Closes #XYZ" with the release ticket number
- [x] Rename QA milestone to `$version` and close the milestone
- [ ] Update https://confluence.owncloud.com/display/PROD/Upcoming+Releases
- [x] Ensure [release template](https://github.com/owncloud/QA/edit/master/tools/release/templates/server_app_release_template.md) is up to date
- [x] Ensure the testplan template ([community](https://github.com/owncloud/QA/tree/master/Server) or [enterprise](https://github.com/owncloud/qa-enterprise/tree/master/Core)) is up to date
- [x] Close the testplan issue

**Comment by jnweiger** [comment]
@timar we have a new release candidate ready for you:
https://github.com/owncloud/richdocuments/releases/tag/v4.2.0
It is in prerelease state, pending your approval and signing. Thanks!

**Comment by timar** [comment]
I uploaded the signed binary to marketplace and made a proper release here on GitHub.
