### ISSUE TITLE
Please help me install richdocuments

### ISSUE THREAD

**Issue by BinhNguyen8x** [owncloud/richdocuments#54]
I've server Owncloud 9 on Ubutu14 , i don't install Richdocuments . Please all help me , please plase :((

**Comment by timar** [comment]
richdocuments was developed for ownCloud 8.2. Reportedly it has problems on ownCloud 9. We will address this issue soon. You also need LibreOffice and LibreOffice Online (loolwsd). LibreOffice Online packages require systemd. Ubuntu 14 does not use systemd. So you need to write your System V init scripts (and ideally contribute them to the project).

**Comment by BinhNguyen8x** [comment]
Thanks sir , sir can't guide me to install libreoffice on current owncloud

2016-06-03 14:30 GMT+07:00 Andras Timar <notifications@github.com>:

**Comment by scolebrook** [comment]
@timar LibreOffice Online packages? From what I've seen it's just source code and you need to compile it yourself (including LibreOffice). Has this changed recently? If so, do you have any links to where packages can be obtained (even if still in alpha/beta/pre-release).

**Comment by timar** [comment]
@scolebrook There are no LibreOffice Online binary packages, as far as I'm concerned. They can be built from source, or there is the updated [CODE VM from Collabora](https://www.collaboraoffice.com/code/) to play with, or there is the commercial offering from Collabora for hosters: [Collabora Online (COOL) v1.0 “Engine”](https://www.collaboraoffice.com/collabora-online-v1-engine/).

**Comment by scolebrook** [comment]
@timar Thank's for the link to Collabora and their v1.0. I've been in contact with them since the start of the year but never saw anything regarding a 1.0. Great news.

Good software takes time but I still don't like the wait very much :smile:.
