### ISSUE TITLE
Clipboard access issue

### ISSUE THREAD

**Issue by chris-fj** [owncloud/richdocuments#545]
Hello, everyone.

I am having trouble when trying to access the clipboard, because when I try to copy from a document, I receive this error

```
Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document
```

My stack is collabora on top of ownCloud, behind Traefik, all running in Docker. The versions are:

Collabora: 
```
COOLWSD version: 24.04.1.4
git hash: [f12ee1f]
```

ownCloud: `10.14.0 (stable)`

As noted by a kind maintainer (vmiklos) in the Collabora discussion page (https://github.com/CollaboraOnline/online/discussions/9038), The "Advanced integration" section in the docs (https://sdk.collaboraonline.com/docs/advanced_integration.html#allow-the-clipboard-permission-query) specifies that the `iframe` of Collabora must contain the attributes `clipboard-read` and `clipboard-write`, none of which are present in the HTML when opening and inspecting the elements of a document (and they should be). 

Thanks for your attention

**Comment by krzys-h** [comment]
I started running into this issue after a recent upgrade, so this is definitely a regression. I'm not certain which component is causing this problem as I upgraded everything at once, but I can confirm that another server running nextcloud + their version of the integration with the same version of Collabora works fine, so it's either this app, or owncloud itself.

**Comment by chris-fj** [comment]
Commenting here as well, updating the collabora version to [`24.04.5.2.1`](https://hub.docker.com/layers/collabora/code/24.04.5.2.1/images/sha256-b2cdde5cabb3cfd59933daf3ce55990b258a4a1391d31d54833e436e7b7fc26f?context=explore) and the issue is gone for me. I have kept the same version for ownCloud. Thanks for the pointers and the support.
