### ISSUE TITLE
I got cURL error 7. help me please.

### ISSUE THREAD

**Issue by justlomo** [owncloud/richdocuments#59]
I just complied loolwsd and loleaflet.
and enable richdocuments in owncloud.
but i got this error
"cURL error 7: Failed to connect to 192.168.38.107 port 9980: Connection refused"
How can i solve it?

my system 
OS ; ubuntu 16.04
owncloud : 8.2.3
PHP : 5.6.22-4
apache : 2.4.18
mysql : Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

**Comment by timar** [comment]
I guess it's solved, because you reported a cURL error 56 later.
