### ISSUE TITLE
help me about error : cURL error 56

### ISSUE THREAD

**Issue by justlomo** [owncloud/richdocuments#62]
my system 
OS ; ubuntu 16.04
owncloud : 8.2.3
PHP : 5.6.22-4
apache : 2.4.18
mysql : Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using EditLine wrapper

I compiled loolwsd and loleaflet.
and enabled richdocuments in owncloud 8.2.3.
I got error.
"Collabora Online unknown error: cURL error 56: Recv failure: Connection reset by peer
Please contact the "http://118.131.9.226:9980" administrator."

what is the problem? any idea about it?
Tell me please.

**Comment by timar** [comment]
First try curl from the command line:
`curl -v http://118.131.9.226:9980`
It gives a more detailed error message. My guess is that you are using loolwsd with SSL support, and you should use https:// not http://. Of course SSL cert and key has to be set up correctly.

**Comment by timar** [comment]
Closing, because this discussion did not go any further.
