### ISSUE TITLE
Localization of 'richdocuments' app

### ISSUE THREAD

**Issue by timar** [owncloud/richdocuments#65]
Hello @deepdiver and @felixboehm,

The current contents of richdocuments/l10n directory is outdated, and
most of the strings are unused.

I read
https://doc.owncloud.org/server/9.1/developer_manual/app/l10n.html and I
learned that ownCloud’s translation system is powered by Transifex. Can
you please help me to add 'richdocuments' to Transifex? I'd like to know
more about the translation process, i.e.,
1) how to extract translatable strings
2) how to update templates in Transifex
3) how to download translations from Transifex
Is there a HOWTO about this somewhere?

My user name at transifex.com is 'timar'.

Thanks,
-- 
Andras Timar
Product Development Manager
Collabora Productivity Ltd.
https://collaboraoffice.com/

**Comment by timar** [comment]
Thanks @DeepDiver1975 for your help. 

I tried to join the Hungarian ownCloud translation team on Transifex.com. Who approves applications? I did not get any feedback for days.

How often / when do we get updates from Transifex?

**Comment by DeepDiver1975** [comment]
> How often / when do we get updates from Transifex?

every night

> I tried to join the Hungarian ownCloud translation team on Transifex.com. Who approves applications? I did not get any feedback for days.

I'll have a look
