### ISSUE TITLE
experimental status

### ISSUE THREAD

**Issue by timar** [owncloud/richdocuments#73]
Hi @DeepDiver1975,

We would like this app to be non-experimental. How to proceed?
## Thanks,

Andras Timar
Product Development Manager
Collabora Productivity Ltd.
https://collaboraoffice.com/

**Comment by enoch85** [comment]
I also think that it should be possible to activate directly from the app store without having to do anything else than just "activate". That would get a much broader audience.

**Comment by DeepDiver1975** [comment]
@timar as soon as the app has been uploaded by you to the appstore we can set the status accordingly to no longer display the app as experimental.

I hope this helps - otherwise please ping me on irc (what you already did but I was offline :cry: )

**Comment by timar** [comment]
The app is still experimental. https://apps.owncloud.com/content/show.php?action=content&content=174727

**Comment by enoch85** [comment]
ping @DeepDiver1975  --^

**Comment by timar** [comment]
richdocuments is 'Approved' now. Thanks.
