### ISSUE TITLE
Default Font:

### ISSUE THREAD

**Issue by kieranr** [owncloud/richdocuments#75]
Hi, 

The default font when opening a document is "Open Sans"

How can this be tweaked so that there is the ability to change the default font.
(And where does this app get it's list of available fonts from ?)

Cheers
KR

**Comment by timar** [comment]
You get the empty file from core/templates/filetemplates/ directory of your ownCloud installation. The list of available fonts is coming from the LibreOffice Online server, it has all fonts that are present in LibreOffice jails. Normally when one installs LibreOffice Online, the so called 'systemplate' will contain all fonts that are installed on the system, so it depends on the font list of the host after all.
