### ISSUE TITLE
Confusing Name for End-Users

### ISSUE THREAD

**Issue by MariusBluem** [owncloud/richdocuments#77]
Isn't the Name "Collabora Online" a bit confusing for end-users? A name like "Documents" would be much more clear for them (e.g. app-menu, personal settings).

**Comment by mar1u5** [comment]
According to #90 it is now called **Office** 👍 However: We are still calling it Collabora Online in the "Personal"-Menu and i think this is confusing 😕 ...maybe we can take "Office" here too 😉

**Comment by jancborchardt** [comment]
@mar1u5 good find! Do you want to submit a pull request for this? Quite an easy one, just look for »Collabora Online« where it’s used in the context of the personal settings and replace it with »Office« too. :)

**Comment by jospoortvliet** [comment]
If it fits I'd say let's keep saying Collabora Online. It is what this tool is called and some branding is a good not bad thing.

**Comment by jancborchardt** [comment]
It’s called »Office« in the app store, app navigation, and top bar when the app is open. Only makes sense to have it be called that in the settings as well – otherwise there will be confusion. It was just an oversight of not changing it there too, we need it to be consistent.

**Comment by jancborchardt** [comment]
Fix at https://github.com/owncloud/richdocuments/pull/96

**Comment by timar** [comment]
Pull request #96 was not merged in the end.
