### ISSUE TITLE
richdocuments not working with encryption

### ISSUE THREAD

**Issue by SpiGAndromeda** [owncloud/richdocuments#97]
Hi,

I also posted this issue in the nextcloud support forum but they suggested to post this issue here:
[https://help.nextcloud.com/t/collabora-not-working-with-encryption/1913](url)

I am using Collabora via the docker container. OS is Ubuntu 14.04. Before you ask ... CONFIG_AUFS_XATTR=y is activated in the kernel.

The Nextcloud configuration:
"system":
 {
        "instanceid": "oc42b8zohyfj",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "localhost",
            "**_REMOVED SENSITIVE VALUE**_"
        ],
        "datadirectory": "**_REMOVED SENSITIVE VALUE**_",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.52.0",
        "dbname": "nextcloud_database",
        "dbhost": "localhost",
        "dbtableprefix": "nc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_smtphost": "smtp.gmail.com",
        "mail_from_address": "**_REMOVED SENSITIVE VALUE**_",
        "mail_domain": "gmail.com",
        "mail_smtpauth": 1,
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "memcache.local": "\OC\Memcache\APCu",
        "theme": "fancy",
        "loglevel": 3,
        "maintenance": false,
        "singleuser": false,
        "htaccess.RewriteBase": "\/owncloud",
        "integrity.check.disabled": true,
        "mail_smtpauthtype": "LOGIN",
        "default_language": "de",
        "defaultapp": "files",
        "enable_previews": true,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 5,
        "forcessl": true,
        "forceSSLforSubdomains": true
    }

"apps": {
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/owncloud.spigomaniac.de"
        }
    }

So i get the following error if I try to open any document with richdocuments:
![screenshot 2016-07-25 14 11 20](https://cloud.githubusercontent.com/assets/15141351/17272211/d444ab9e-5690-11e6-93f2-a56e2800e9d7.png)

I guess the key error message is: Private Key missing for user: please try to log-out and log-in again.

Fristly I already confirmed the encryption as the reason, because with a test user and temporairily disabled encryption it is fully working. 
Secondly I used the CODE VM for testing. I upgraded owncloud to the latest version of nextcloud, enabled encryption and it's working! Under the assumption that this richdocuments app is just an updeted version of the app used in the CODE VM some updates between this versions seems to have broken the encryption support.

Another issue that could be connected to this one is the file loading delay (20s - 30s):
![screenshot 2016-07-30 20 19 16](https://cloud.githubusercontent.com/assets/15141351/17272293/061c65ba-5693-11e6-84d7-0c0840f504cf.png)

**Comment by ezraholm50** [comment]
I also have this problem, disabling encryption makes it work. I have no way of upgrading, running the latest cloud. Any other update on solving this?

**Comment by viorel-m** [comment]
Same here, but I've noticed an error in apache log every time i try to open a file : 

> [Wed Aug 31 13:13:18.210968 2016] [:error] [pid 7247] [client 192.168.10.1:35950] PHP Fatal error:  Uncaught exception 'Exception' with message 'Session has been closed - no further changes to the session are allowed' in /var/www/owncloud/lib/private/Session/Memory.php:120\nStack trace:\n#0 /var/www/owncloud/lib/private/Session/Memory.php(53): OC\\Session\\Memory->validateSession()\n#1 /var/www/owncloud/lib/private/Session/CryptoSessionData.php(164): OC\\Session\\Memory->set('encrypted_sessi...', '5a998925ffcd164...')\n#2 /var/www/owncloud/lib/private/Session/CryptoSessionData.php(67): OC\\Session\\CryptoSessionData->close()\n#3 [internal function]: OC\\Session\\CryptoSessionData->__destruct()\n#4 {main}\n  thrown in /var/www/owncloud/lib/private/Session/Memory.php on line 120

**Comment by chrsch** [comment]
Maybe this can be fixed like this one https://github.com/owncloud/core/issues/10236

**Comment by joeyjy** [comment]
I met the same problem, once enable server-side-encryption, the iframe will display like what @SpiGAndromeda showed. It will be appreciated for fixing this issue, anyone can help? :P

**Comment by timar** [comment]
It's fixed in 1.1.23 release.
